"""Recognizer bench -- shared infra + offline checks.

The measurement lane now lives in unified_bench.py (the single-Gemma, direct-Hebrew harness).
This module keeps only what unified_bench imports (to_scorer_schema and the re-exposed
llama-server config) plus two offline, no-GPU utilities:
    --audit   scorer references + the recognizer's tests (never measure with a broken
              scorer)
    --cases   regenerate CASES.md

The legacy translated harness (make_translator, plan, run_recognizer, run_perfect_en) was
retired with the translated path (2026-09-12); its prompt imports are gone. Superseded lanes
live in git history; their numbers stay under results/ and results/HISTORY.md.
"""
import argparse
import atexit
import contextlib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
# The component lives in the harden2 tree; the bench measures it IN PLACE (dedup ruling
# 2026-09-02: no copies in two homes).
_HOME = os.path.join(ROOT, "projects", os.environ.get("MVD_HOME", "integration_harden2"))
sys.path.insert(0, _HOME)          # harden2 root: import the recognizer package from here
sys.path.insert(0, HERE)

from gemma import server as gemma_process
from gemma.client import Gemma
from system.fatal import die
from system.supervisor import Supervisor
from cases_commands import CASES as CMD_CASES, VERBOSE_CASES, EMERGENCY_CASES
from cases_perception import PERC100, SLANG20, check_refs

PORT = 18091                                    # the bench Gemma never collides with the app's
THINKING = os.environ.get("GEMMA4_THINK") == "1"  # the bench A/B arm: GEMMA4_THINK=1 = on


@contextlib.contextmanager
def gemma_server():
    """Start Gemma the way the app does (owner ruling 2026-09-23): the supervisor and
    gemma.server.process(), on the bench port. -> a gemma.client.Gemma inside the
    with-block. atexit stops the server even when a bench crashes, so no GPU process is
    left behind."""
    supervisor = Supervisor()
    atexit.register(supervisor.stop_all)
    log_dir = tempfile.mkdtemp(prefix="bench-gemma-")
    handle = supervisor.start(gemma_process.process(log_dir, port=PORT, thinking=THINKING))
    if not handle.wait_up(300):
        die(f"the bench Gemma was not ready after 300 s; log: {log_dir}/proc-gemma.log")

    yield Gemma(PORT)

    supervisor.stop_all()
    return


# The planner speaks the phone app schema (dx/dy/dz); the scorer speaks x/y/z.
SCORER_KEY = {"dx": "x", "dy": "y", "dz": "z", "degrees": "degrees", "seconds": "seconds"}


def to_scorer_schema(mission):
    """dx/dy/dz -> x/y/z; velocity is dropped (the scorer judges geometry, the app clamps it)."""
    out = []
    for step in mission:
        converted = {"type": step["type"]}
        for k, v in step.items():
            if k in SCORER_KEY:
                converted[SCORER_KEY[k]] = v
        out.append(converted)
    return out


def audit():
    """No GPU: every hand-written English reference must satisfy its own keyword groups,
    and the recognizer's tests (test/test_recognizer.py, the rules against their
    evidence) must pass."""
    bad = check_refs()
    tests = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider",
         os.path.join(_HOME, "test", "test_recognizer.py")],
        cwd=_HOME,
        capture_output=True,
        text=True
    )
    if tests.returncode != 0:
        bad.append("recognizer tests FAILED:\n" + tests.stdout[-2000:])
    if bad:
        print("\n".join(str(b) for b in bad))
        raise SystemExit(1)
    print("audit CLEAN: scorer references and recognizer tests all pass")


def write_cases_md():
    """Regenerate CASES.md, the human-readable inventory of every tested sentence."""
    def expected_text(e):
        if e is None:
            return "open-ended (validity only)"
        if e == []:
            return "[] (no action)"
        return "; ".join(f"{t}" + (f" {k}={v}" if k else "") for t, k, v in e)

    with open(os.path.join(HERE, "CASES.md"), "w") as f:
        f.write("# Every sentence the bench tests\n\nGenerated by `python3 bench.py --cases`"
                " -- edit the cases_*.py files, not this.\n")
        f.write(f"\n## Commands ({len(CMD_CASES)}) -- scored as mission JSON\n\n"
                "| # | id | Hebrew | English reference | expected |\n|---|---|---|---|---|\n")
        for i, (name, he, en, exp) in enumerate(CMD_CASES, 1):
            f.write(f"| {i} | {name} | {he} | {en} | {expected_text(exp)} |\n")
        f.write(f"\n## Verbose commands ({len(VERBOSE_CASES)})\n\n"
                "| # | id | Hebrew | English reference | expected |\n|---|---|---|---|---|\n")
        for i, (name, he, en, exp) in enumerate(VERBOSE_CASES, 1):
            f.write(f"| {i} | {name} | {he} | {en} | {expected_text(exp)} |\n")
        f.write(f"\n## Emergency ({len(EMERGENCY_CASES)}) -- must be caught by stage 0\n\n"
                "| # | id | Hebrew |\n|---|---|---|\n")
        for i, (name, he) in enumerate(EMERGENCY_CASES, 1):
            f.write(f"| {i} | {name} | {he} |\n")
        f.write(f"\n## Perception ({len(PERC100)}) -- scored by keyword preservation\n\n"
                "| # | id | depth | Hebrew | English reference |\n|---|---|---|---|---|\n")
        for i, (name, he, en, g, depth) in enumerate(PERC100, 1):
            f.write(f"| {i} | {name} | {depth} | {he} | {en} |\n")
        f.write(f"\n## Military phraseology ({len(SLANG20)})\n\n"
                "| # | id | class | Hebrew | English reference |\n|---|---|---|---|---|\n")
        for i, (name, he, en, g, klass) in enumerate(SLANG20, 1):
            f.write(f"| {i} | {name} | {klass} | {he} | {en} |\n")
    print(f"CASES.md written: {len(CMD_CASES)}+{len(VERBOSE_CASES)} commands, "
          f"{len(EMERGENCY_CASES)} emergency, {len(PERC100)} perception, {len(SLANG20)} military")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--audit", action="store_true", help="offline scorer + self-test check, no GPU")
    parser.add_argument("--cases", action="store_true", help="regenerate CASES.md and exit")
    args = parser.parse_args()
    if args.cases:
        write_cases_md()
    else:
        audit()   # default: the offline audit. The measurement lane is unified_bench.py.


if __name__ == "__main__":
    main()
