# -*- coding: utf-8 -*-
"""Fresh held-out typing set (2026-09-18): 200 NEW Hebrew utterances, authored to be non-repeating
and field-realistic, NOT drawn from the recognizer's dev set. Purpose: measure the deterministic
bypass vs the Gemma planner at TYPING a sentence without the dataset-bias that flatters the bypass.

Case = (name, hebrew, gt).  gt is the intent type:
  "move"     = the drone should physically ACT (fly / rotate / gimbal / hover / follow-me / take off /
               land / wait-in-a-mission). A mission is the right output.
  "not_move" = a perception/vision request (see / count / highlight / find / track-an-object / where-is),
               a status question, or a non-action (negation / acknowledgement). No mission.
Borderline calls documented in the review notes; the owner may relabel. Author knew the bypass regexes,
so treat the bypass numbers here as an upper bound, not blind.
"""

FRESH = [
 # ---- MOVE: directional + distance (varied verbs / numbers / units) ----
 ("m_fwd8", "טוס קדימה שמונה מטרים", "move"),
 ("m_right3", "זוז ימינה שלושה מטרים", "move"),
 ("m_back12", "עוף אחורה שנים עשר מטרים", "move"),
 ("m_adv7", "התקדם שבעה מטרים", "move"),
 ("m_left45", "סטה שמאלה ארבעה מטרים וחצי", "move"),
 ("m_fwd1", "נוע קדימה מטר אחד", "move"),
 ("m_right20", "טוס ימינה עשרים מטר", "move"),
 ("m_down2", "רד שני מטרים", "move"),
 ("m_up6", "עלה שבעה מטרים וחצי", "move"),
 ("m_back_half", "טוס אחורה חצי מטר", "move"),
 ("m_fwd25", "קדימה עשרים וחמישה מטר", "move"),
 ("m_left9", "שמאלה תשעה מטרים", "move"),
 ("m_up15", "תעלה חמישה עשר מטר", "move"),
 ("m_down8", "תרד שמונה מטרים", "move"),
 ("m_right13", "תזוז ימינה שלושה עשר מטר", "move"),
 ("m_fwd_two_half", "טוס קדימה שניים וחצי מטר", "move"),
 ("m_back6", "אחורה שישה מטרים", "move"),
 ("m_up_one", "עלה מטר אחד למעלה", "move"),
 ("m_left11", "זוז אחד עשר מטרים שמאלה", "move"),
 ("m_fwd30", "התקדם שלושים מטר קדימה", "move"),
 # ---- MOVE: rotations ----
 ("m_cw90", "תסתובב תשעים מעלות ימינה", "move"),
 ("m_ccw60", "תסתובב שישים מעלות נגד כיוון השעון", "move"),
 ("m_cw180", "פנה מאה שמונים מעלות ימינה", "move"),
 ("m_yaw30left", "סובב שלושים מעלות שמאלה", "move"),
 ("m_spin_full", "עשה סיבוב שלם", "move"),
 ("m_cw45", "הסתובב ארבעים וחמש מעלות עם השעון", "move"),
 ("m_ccw120", "תסתובב מאה עשרים מעלות נגד השעון", "move"),
 ("m_turn_right90", "פנה ימינה תשעים מעלות", "move"),
 ("m_spin2", "תעשה שני סיבובים שלמים", "move"),
 ("m_cw270", "הסתובב מאתיים שבעים מעלות", "move"),
 ("m_ccw15", "סובב חמש עשרה מעלות שמאלה", "move"),
 ("m_half_turn", "הסתובב חצי סיבוב שלם", "move"),
 # ---- MOVE: takeoff / land ----
 ("m_takeoff1", "המרא עכשיו", "move"),
 ("m_takeoff2", "קח אותנו לאוויר", "move"),
 ("m_takeoff3", "תמריא כבר לאוויר", "move"),
 ("m_takeoff4", "תתרומם מהקרקע", "move"),
 ("m_land1", "תנחת כאן", "move"),
 ("m_land2", "תנחת בעדינות", "move"),
 ("m_land3", "רד ונחת על הקרקע", "move"),
 ("m_land4", "הנחת את הרחפן", "move"),
 # ---- MOVE: relative / conversational (the ones Gemma tends to over-reject) ----
 ("m_higher1", "טוס טיפה יותר גבוה", "move"),
 ("m_higher2", "עלה עוד טיפה", "move"),
 ("m_lower1", "רד קצת", "move"),
 ("m_lower2", "תרד עוד מעט למטה", "move"),
 ("m_closer", "תתקרב אליי", "move"),
 ("m_farther", "תתרחק קצת אחורה", "move"),
 ("m_slow_fwd", "תתקדם לאט קדימה", "move"),
 ("m_a_bit_left", "זוז טיפה שמאלה", "move"),
 ("m_a_bit_right", "קצת ימינה", "move"),
 ("m_hover1", "רחף במקום", "move"),
 ("m_hover2", "תעמוד במקום באוויר", "move"),
 ("m_hold", "תישאר איפה שאתה", "move"),
 ("m_up_more", "עוד קצת למעלה", "move"),
 ("m_come_down_bit", "בוא רד קצת", "move"),
 ("m_ascend_slow", "עלה לאט", "move"),
 ("m_nudge_fwd", "זוז קצת קדימה", "move"),
 # ---- MOVE: follow / orbit / return / scan ----
 ("m_follow_me", "עקוב אחריי", "move"),
 ("m_follow_him", "עקוב אחרי האיש שהולך שם", "move"),
 ("m_track_me", "תעקוב אחריי כל הזמן", "move"),
 ("m_come_home", "טוס בחזרה אליי", "move"),
 ("m_return", "תחזור לנקודת ההמראה", "move"),
 ("m_orbit_out", "תקיף את האזור", "move"),
 ("m_orbit_in", "תסרוק במעגל סביב הנקודה", "move"),
 ("m_wave", "תנופף לשלום", "move"),
 ("m_scan_area", "סרוק את השטח", "move"),
 ("m_circle_me", "הקף אותי", "move"),
 # ---- MOVE: compound multi-step ----
 ("m_c1", "עלה חמישה מטרים ואז טוס קדימה עשרה מטרים", "move"),
 ("m_c2", "המרא, עלה שלושה מטרים ונחת", "move"),
 ("m_c3", "טוס אחורה שני מטרים ואז שמאלה ארבעה מטרים", "move"),
 ("m_c4", "הסתובב תשעים מעלות ואז התקדם שבעה מטרים", "move"),
 ("m_c5", "עלה שני מטרים, המתן חמש שניות ורד", "move"),
 ("m_c6", "טוס קדימה חמישה מטרים ואז הסתובב מאה שמונים מעלות", "move"),
 ("m_c7", "קח גובה עשרה מטרים ואז סע ימינה שלושה מטרים", "move"),
 ("m_c8", "תמריא, תעלה גבוה ותעשה סיבוב", "move"),
 ("m_c9", "רד שלושה מטרים ואז נחת", "move"),
 ("m_c10", "זוז שמאלה חמישה מטרים ואז קדימה שניים", "move"),
 ("m_c11", "הסתובב שישים מעלות שמאלה ואז עלה מטר", "move"),
 ("m_c12", "טוס קדימה, המתן שתי שניות ואז אחורה", "move"),
 ("m_c13", "עלה ארבעה מטרים ואז תעקוב אחריי", "move"),
 ("m_c14", "פנה ימינה תשעים ואז התקדם עשרה מטרים", "move"),
 # ---- MOVE: gimbal + wait + misc physical ----
 ("m_gim_down", "כוון את המצלמה למטה", "move"),
 ("m_gim_up", "הפנה את המצלמה למעלה", "move"),
 ("m_gim_fwd", "יישר את המצלמה קדימה", "move"),
 ("m_wait3", "המתן שלוש שניות", "move"),
 ("m_wait_then", "חכה חמש שניות ואז המשך", "move"),
 ("m_fwd_far", "טוס רחוק קדימה", "move"),
 ("m_dash_left", "תזנק שמאלה", "move"),
 ("m_back_slow", "תיסע אחורה לאט", "move"),
 ("m_up_high", "תעלה גבוה מאוד", "move"),
 ("m_down_ground", "רד קרוב לקרקע", "move"),
 ("m_strafe_r", "החלק ימינה חמישה מטרים", "move"),
 ("m_diag", "טוס קדימה וגם ימינה", "move"),
 ("m_reposition", "תזוז למקום אחר", "move"),
 ("m_align", "תסתדר מולי", "move"),
 ("m_approach_bldg", "תתקרב לבניין", "move"),
 ("m_over_there", "טוס לשם", "move"),
 ("m_this_way", "בוא לכאן", "move"),
 ("m_lift", "תרים את עצמך שני מטרים", "move"),
 ("m_creep_fwd", "תתקדם קצת קדימה בזהירות", "move"),
 ("m_swing_left", "תנוע בקשת שמאלה", "move"),

 # ---- NOT_MOVE: see / describe ----
 ("p_see1", "מה אתה רואה מולך", "not_move"),
 ("p_see2", "תאר לי את הסצנה", "not_move"),
 ("p_see3", "מה קורה שם למטה", "not_move"),
 ("p_see4", "ספר לי מה אתה מזהה", "not_move"),
 ("p_see5", "תן סקירה של האזור", "not_move"),
 ("p_see6", "מה יש בתמונה עכשיו", "not_move"),
 ("p_see7", "תסתכל ותגיד לי מה יש", "not_move"),
 ("p_see8", "במה אתה מבחין", "not_move"),
 ("p_see9", "תאר את הרחוב", "not_move"),
 ("p_see10", "מה נמצא בשדה הראייה", "not_move"),
 ("p_see11", "תעשה סקירה כללית", "not_move"),
 ("p_see12", "מה אתה רואה בצד ימין", "not_move"),
 # ---- NOT_MOVE: count ----
 ("p_cnt1", "כמה בני אדם יש בשטח", "not_move"),
 ("p_cnt2", "ספור את המכוניות ברחוב", "not_move"),
 ("p_cnt3", "כמה חלונות יש בבניין", "not_move"),
 ("p_cnt4", "כמה כלי רכב חונים כאן", "not_move"),
 ("p_cnt5", "תספור את העצים", "not_move"),
 ("p_cnt6", "כמה דלתות יש בקומה הראשונה", "not_move"),
 ("p_cnt7", "כמה אנשים ליד הרכב", "not_move"),
 ("p_cnt8", "ספור לי את האופנועים", "not_move"),
 ("p_cnt9", "כמה מבנים יש באזור", "not_move"),
 ("p_cnt10", "כמה ילדים במגרש", "not_move"),
 ("p_cnt11", "תגיד לי כמה משאיות יש", "not_move"),
 ("p_cnt12", "כמה קומות יש למגדל", "not_move"),
 ("p_cnt13", "ספור את הדגלים", "not_move"),
 ("p_cnt14", "כמה כלבים אתה רואה", "not_move"),
 ("p_cnt15", "כמה מכוניות אדומות יש", "not_move"),
 # ---- NOT_MOVE: highlight / mark / find ----
 ("p_hl1", "סמן את המכונית האדומה", "not_move"),
 ("p_hl2", "הדגש את הבניין הגבוה", "not_move"),
 ("p_hl3", "מצא את הכניסה הראשית", "not_move"),
 ("p_hl4", "סמן לי את האדם עם החולצה הכחולה", "not_move"),
 ("p_hl5", "הדגש את הגג האדום", "not_move"),
 ("p_hl6", "מצא את האופניים ליד הגדר", "not_move"),
 ("p_hl7", "סמן את החלון השבור", "not_move"),
 ("p_hl8", "הדגש את השלט בכניסה", "not_move"),
 ("p_hl9", "מצא את הרכב הלבן", "not_move"),
 ("p_hl10", "סמן את הדלת הפתוחה", "not_move"),
 ("p_hl11", "הדגש את העמוד בפינה", "not_move"),
 ("p_hl12", "מצא את הפח הכתום", "not_move"),
 ("p_hl13", "סמן את המדרגות", "not_move"),
 ("p_hl14", "הדגש את הצינור על הגג", "not_move"),
 ("p_hl15", "מצא את השער הצפוני", "not_move"),
 ("p_hl16", "סמן את הברז ליד הקיר", "not_move"),
 ("p_hl17", "הדגש את המכונית שחונה על המדרכה", "not_move"),
 ("p_hl18", "מצא את האדם שרץ", "not_move"),
 ("p_hl19", "סמן את הארגז הגדול", "not_move"),
 ("p_hl20", "הדגש את הסולם", "not_move"),
 # ---- NOT_MOVE: track / focus on a scene object (visual) ----
 ("p_tr1", "תמקד על המכונית הכחולה במסך", "not_move"),
 ("p_tr2", "תמקד באדם עם התיק", "not_move"),
 ("p_tr3", "תתמקד בכלב שרץ", "not_move"),
 ("p_tr4", "תמקד על האופנוע הנוסע", "not_move"),
 ("p_tr5", "תמקד במשאית שיוצאת", "not_move"),
 ("p_tr6", "תתמקד בילד עם הכדור", "not_move"),
 ("p_tr7", "תמקד באדם שעל האופניים", "not_move"),
 ("p_tr8", "תמקד ברכב האדום שמתרחק", "not_move"),
 # ---- NOT_MOVE: presence / is-there ----
 ("p_is1", "יש מישהו על הגג", "not_move"),
 ("p_is2", "האם יש רכב חונה בכניסה", "not_move"),
 ("p_is3", "יש אנשים בשטח", "not_move"),
 ("p_is4", "האם הדלת פתוחה", "not_move"),
 ("p_is5", "יש מכשול לפניך", "not_move"),
 ("p_is6", "האם יש כלב בחצר", "not_move"),
 ("p_is7", "יש עשן באזור", "not_move"),
 ("p_is8", "האם המגרש ריק", "not_move"),
 ("p_is9", "יש תנועה ברחוב", "not_move"),
 ("p_is10", "האם יש דגל על הבניין", "not_move"),
 ("p_is11", "יש אור בחלון", "not_move"),
 ("p_is12", "האם מישהו מתקרב", "not_move"),
 # ---- NOT_MOVE: status / meta questions ----
 ("p_st1", "מה אחוז הסוללה", "not_move"),
 ("p_st2", "כמה סוללה נשארה", "not_move"),
 ("p_st3", "באיזה גובה אתה נמצא", "not_move"),
 ("p_st4", "מה המיקום שלך", "not_move"),
 ("p_st5", "האם אתה מחובר", "not_move"),
 ("p_st6", "מה מהירות הרוח", "not_move"),
 ("p_st7", "כמה זמן אתה באוויר", "not_move"),
 ("p_st8", "מה הטמפרטורה בחוץ", "not_move"),
 ("p_st9", "לאיזה כיוון אתה פונה", "not_move"),
 ("p_st10", "מה חוזק האות", "not_move"),
 ("p_st11", "האם יש קליטה טובה", "not_move"),
 ("p_st12", "כמה רחוק אתה ממני", "not_move"),
 ("p_st13", "מה הסטטוס שלך", "not_move"),
 # ---- NOT_MOVE: spatial-relation perception ----
 ("p_sp1", "מה נמצא ליד המכונית האדומה", "not_move"),
 ("p_sp2", "מה יש מאחורי הבניין", "not_move"),
 ("p_sp3", "תאר את מה שמעל הדלת", "not_move"),
 ("p_sp4", "מה נמצא בין שני העצים", "not_move"),
 ("p_sp5", "מה יש מתחת לגשר", "not_move"),
 ("p_sp6", "מי עומד ליד הכניסה", "not_move"),
 ("p_sp7", "מה נמצא בפינה השמאלית", "not_move"),
 ("p_sp8", "מה יש על הספסל", "not_move"),
 ("p_sp9", "תאר את מה שמימין למשאית", "not_move"),
 ("p_sp10", "מה נמצא בקצה הרחוב", "not_move"),
 ("p_sp11", "מה יש ברקע", "not_move"),
 ("p_sp12", "מי יושב על הגדר", "not_move"),
 # ---- NOT_MOVE: negation / non-action / acknowledgement ----
 ("p_neg1", "אל תמריא בכלל", "not_move"),
 ("p_neg2", "אל תמשיך לתאר", "not_move"),
 ("p_neg3", "תפסיק לדבר", "not_move"),
 ("p_neg4", "לא עכשיו", "not_move"),
 ("p_neg5", "עזוב, לא משנה", "not_move"),
 ("p_neg6", "תודה רבה", "not_move"),
 ("p_neg7", "כל הכבוד", "not_move"),
 ("p_neg8", "רגע, אל תעשה כלום", "not_move"),
]
