# -*- coding: utf-8 -*-
"""Hand-authored English glosses for cases_typing_fresh.FRESH (best-case translation ceiling).
Used to test whether Gemma types command intent better on English than on raw Hebrew."""
EN = {
 "m_fwd8":"fly forward 8 meters","m_right3":"move right 3 meters","m_back12":"fly back 12 meters",
 "m_adv7":"advance 7 meters","m_left45":"veer left 4.5 meters","m_fwd1":"move forward 1 meter",
 "m_right20":"fly right 20 meters","m_down2":"descend 2 meters","m_up6":"go up 7 and a half meters",
 "m_back_half":"fly back half a meter","m_fwd25":"forward 25 meters","m_left9":"left 9 meters",
 "m_up15":"climb 15 meters","m_down8":"descend 8 meters","m_right13":"move right 13 meters",
 "m_fwd_two_half":"fly forward two and a half meters","m_back6":"back 6 meters","m_up_one":"go up one meter",
 "m_left11":"move 11 meters left","m_fwd30":"advance 30 meters forward",
 "m_cw90":"rotate 90 degrees right","m_ccw60":"rotate 60 degrees counterclockwise","m_cw180":"turn 180 degrees right",
 "m_yaw30left":"rotate 30 degrees left","m_spin_full":"do a full spin","m_cw45":"rotate 45 degrees clockwise",
 "m_ccw120":"rotate 120 degrees counterclockwise","m_turn_right90":"turn right 90 degrees","m_spin2":"do two full spins",
 "m_cw270":"rotate 270 degrees","m_ccw15":"rotate 15 degrees left","m_half_turn":"do a full half turn",
 "m_takeoff1":"take off now","m_takeoff2":"take us into the air","m_takeoff3":"take off into the air already",
 "m_takeoff4":"lift off the ground","m_land1":"land here","m_land2":"land gently",
 "m_land3":"descend and land on the ground","m_land4":"land the drone",
 "m_higher1":"fly a bit higher","m_higher2":"go up a little more","m_lower1":"go down a bit",
 "m_lower2":"descend a little more","m_closer":"come closer to me","m_farther":"move a bit farther back",
 "m_slow_fwd":"advance slowly forward","m_a_bit_left":"move a little left","m_a_bit_right":"a little to the right",
 "m_hover1":"hover in place","m_hover2":"hold position in the air","m_hold":"stay where you are",
 "m_up_more":"a bit more up","m_come_down_bit":"come down a bit","m_ascend_slow":"ascend slowly",
 "m_nudge_fwd":"move forward a little",
 "m_follow_me":"follow me","m_follow_him":"follow the man walking there","m_track_me":"keep following me",
 "m_come_home":"fly back to me","m_return":"return to the takeoff point","m_orbit_out":"circle the area",
 "m_orbit_in":"orbit around the point","m_wave":"wave hello","m_scan_area":"scan the area","m_circle_me":"circle around me",
 "m_c1":"go up 5 meters then fly forward 10 meters","m_c2":"take off, go up 3 meters and land",
 "m_c3":"fly back 2 meters then left 4 meters","m_c4":"rotate 90 degrees then advance 7 meters",
 "m_c5":"go up 2 meters, wait 5 seconds and descend","m_c6":"fly forward 5 meters then rotate 180 degrees",
 "m_c7":"gain 10 meters altitude then go right 3 meters","m_c8":"take off, climb high and do a spin",
 "m_c9":"descend 3 meters then land","m_c10":"go left 5 meters then forward 2",
 "m_c11":"rotate 60 degrees left then go up 1 meter","m_c12":"fly forward, wait 2 seconds then back",
 "m_c13":"go up 4 meters then follow me","m_c14":"turn right 90 then advance 10 meters",
 "m_gim_down":"point the camera down","m_gim_up":"point the camera up","m_gim_fwd":"level the camera forward",
 "m_wait3":"wait 3 seconds","m_wait_then":"wait 5 seconds then continue","m_fwd_far":"fly far forward",
 "m_dash_left":"dash left","m_back_slow":"drive back slowly","m_up_high":"go very high",
 "m_down_ground":"descend close to the ground","m_strafe_r":"strafe right 5 meters","m_diag":"fly forward and also right",
 "m_reposition":"move to another spot","m_align":"align in front of me","m_approach_bldg":"approach the building",
 "m_over_there":"fly over there","m_this_way":"come here","m_lift":"lift yourself 2 meters",
 "m_creep_fwd":"move forward a little carefully","m_swing_left":"swing left in an arc",
 "p_see1":"what do you see in front of you","p_see2":"describe the scene for me","p_see3":"what is happening down there",
 "p_see4":"tell me what you recognize","p_see5":"give an overview of the area","p_see6":"what is in the image now",
 "p_see7":"look and tell me what is there","p_see8":"what do you notice","p_see9":"describe the street",
 "p_see10":"what is in the field of view","p_see11":"do a general survey","p_see12":"what do you see on the right",
 "p_cnt1":"how many people are in the area","p_cnt2":"count the cars in the street","p_cnt3":"how many windows are in the building",
 "p_cnt4":"how many vehicles are parked here","p_cnt5":"count the trees","p_cnt6":"how many doors are on the first floor",
 "p_cnt7":"how many people are near the vehicle","p_cnt8":"count the motorcycles for me","p_cnt9":"how many buildings are in the area",
 "p_cnt10":"how many children are on the field","p_cnt11":"tell me how many trucks there are","p_cnt12":"how many floors does the tower have",
 "p_cnt13":"count the flags","p_cnt14":"how many dogs do you see","p_cnt15":"how many red cars are there",
 "p_hl1":"mark the red car","p_hl2":"highlight the tall building","p_hl3":"find the main entrance",
 "p_hl4":"mark the person in the blue shirt for me","p_hl5":"highlight the red roof","p_hl6":"find the bicycle by the fence",
 "p_hl7":"mark the broken window","p_hl8":"highlight the sign at the entrance","p_hl9":"find the white vehicle",
 "p_hl10":"mark the open door","p_hl11":"highlight the pole in the corner","p_hl12":"find the orange bin",
 "p_hl13":"mark the stairs","p_hl14":"highlight the pipe on the roof","p_hl15":"find the northern gate",
 "p_hl16":"mark the tap by the wall","p_hl17":"highlight the car parked on the sidewalk","p_hl18":"find the running person",
 "p_hl19":"mark the large crate","p_hl20":"highlight the ladder",
 "p_tr1":"focus on the blue car on screen","p_tr2":"focus on the person with the bag","p_tr3":"focus on the running dog",
 "p_tr4":"focus on the moving motorcycle","p_tr5":"focus on the truck pulling out","p_tr6":"focus on the child with the ball",
 "p_tr7":"focus on the person on the bicycle","p_tr8":"focus on the red vehicle moving away",
 "p_is1":"is there someone on the roof","p_is2":"is there a vehicle parked at the entrance","p_is3":"are there people in the area",
 "p_is4":"is the door open","p_is5":"is there an obstacle ahead of you","p_is6":"is there a dog in the yard",
 "p_is7":"is there smoke in the area","p_is8":"is the field empty","p_is9":"is there traffic in the street",
 "p_is10":"is there a flag on the building","p_is11":"is there a light in the window","p_is12":"is someone approaching",
 "p_st1":"what is the battery percentage","p_st2":"how much battery is left","p_st3":"what altitude are you at",
 "p_st4":"what is your location","p_st5":"are you connected","p_st6":"what is the wind speed",
 "p_st7":"how long have you been in the air","p_st8":"what is the temperature outside","p_st9":"which direction are you facing",
 "p_st10":"what is the signal strength","p_st11":"is there good reception","p_st12":"how far are you from me","p_st13":"what is your status",
 "p_sp1":"what is next to the red car","p_sp2":"what is behind the building","p_sp3":"describe what is above the door",
 "p_sp4":"what is between the two trees","p_sp5":"what is under the bridge","p_sp6":"who is standing by the entrance",
 "p_sp7":"what is in the left corner","p_sp8":"what is on the bench","p_sp9":"describe what is to the right of the truck",
 "p_sp10":"what is at the end of the street","p_sp11":"what is in the background","p_sp12":"who is sitting on the fence",
 "p_neg1":"do not take off at all","p_neg2":"stop describing","p_neg3":"stop talking","p_neg4":"not now",
 "p_neg5":"never mind, forget it","p_neg6":"thank you very much","p_neg7":"well done","p_neg8":"wait, do not do anything",
}
