"""100 multi-hop perception cases (round 6) = the 45 round-5 cases + 55 new hand-authored ones.
Every case: (name, hebrew, english_reference, keyword_groups, depth).
The english_reference is hand-written and serves as the control arm; it must satisfy its own
keyword groups (verified by check_refs), so any control miss at runtime = scorer bug.
depth: 1 = attributed object, 2 = one link, 3 = two links, 4 = three chained links.
New styles: 20 depth-4 chains; verbose "pinpoint" phrasing where a person narrows the search
with extra simple clauses, including exclusions ("not the one that...")."""
from cases_indirect import INDIRECT_CASES

_REFS45 = {
 "i_mid_windows":  "Highlight the middle windows of the rightmost building",
 "i_third_door":   "Mark the front door of the third house from the left",
 "i_rear_wheel":   "Focus on the rear wheel of the parked motorcycle",
 "i_top_windows":  "Count the windows on the top floor of the tower",
 "i_roof_corner":  "Mark the top left corner of the red roof",
 "i_chimney":      "Highlight the chimney of the lowest house on the street",
 "i_back_entrance":"Find the back entrance of the big warehouse",
 "i_ladder_pickup":"Mark the ladder on the roof of the white pickup",
 "i_car_by_red":   "Highlight the car adjacent to the person with the red attire",
 "i_orange_cap":   "Track the person with the orange cap",
 "i_door_by_coat": "Mark the door next to the man with the black coat",
 "i_bike_fence":   "Focus on the bicycle leaning on the fence of the yellow house",
 "i_dog_by_dress": "Track the dog walking beside the woman in the white dress",
 "i_kid_bag":      "Highlight the bag that the child with the green shirt is holding",
 "i_tree_truck":   "Mark the tree behind the yellow truck",
 "i_win_over_door":"Find the window above the blue door",
 "i_cars_by_flag": "Count the cars parked in front of the building with the flag",
 "i_bench_trees":  "Highlight the bench between the two tall trees",
 "i_behind_moto":  "Track the vehicle driving behind the red motorcycle",
 "i_man_on_roof":  "Mark the man standing on the roof of the white building",
 "i_box_by_man":   "Highlight the box next to the man standing on the roof of the white building",
 "i_girl_balloon": "Track the girl with the balloon walking near the woman with the stroller",
 "i_car_between":  "Mark the car parked between the white pickup and the red truck",
 "i_door_by_tree": "Find the door of the house facing the tallest tree",
 "i_sign_awning":  "Focus on the sign above the entrance of the store with the green awning",
 "i_front_tire":   "Highlight the front tire of the car parked closest to the gate",
 "i_bench_fountain":"Count the people sitting on the benches to the left of the fountain",
 "i_exit_gray":    "Track the person who came out of the door of the gray building",
 "i_second_car":   "Mark the second vehicle from the left in the front row of the parking lot",
 "i_dark_stain":   "Find the dark stain on the wall to the right of the big window",
 "i_glasses_talk": "Highlight the man with the glasses talking to the woman in the yellow shirt",
 "i_truck_boat":   "Track the truck towing the white boat",
 "i_empty_chair":  "Mark the empty chair next to the round table",
 "i_bird_cable":   "Focus on the bird sitting on the cable between the two poles",
 "i_fence_gap":    "Find the opening in the fence behind the blue container",
 "i_main_steps":   "Count the steps at the main entrance of the tall building",
 "i_helmet_mid":   "Highlight the rider with the yellow helmet in the middle of the group",
 "i_cat_climb":    "Track the cat climbing the tree next to the wall",
 "i_lean_silver":  "Mark the guy leaning on the silver car",
 "i_flag_low":     "Find the flag flying above the roof of the low structure",
 "i_broken_window":"Highlight the broken window on the bottom floor of the abandoned building",
 "i_last_convoy":  "Track the last car in the convoy",
 "i_big_tent":     "Mark the biggest tent at the edge of the field",
 "i_crane_arm":    "Focus on the arm of the crane above the construction site",
 "i_boats_pier":   "Count the boats tied to the northern pier",
}

_NEW55 = [
 # -- 20 depth-4 chains --
 ("j_bag_chain",    "הדגש את התיק שמונח ליד הכיסא שמאחורי הדלפק של החנות עם הסוכך הכחול",
    "Highlight the bag lying next to the chair behind the counter of the store with the blue awning",
    [["bag","backpack"],["next","beside","near"],["chair"],["behind"],["counter"],["store","shop"],["blue"],["awning","canopy"]], 4),
 ("j_bird_branch",  "סמן את הציפור שעל הענף של העץ שליד הכניסה לבניין האפור",
    "Mark the bird on the branch of the tree next to the entrance of the gray building",
    [["bird"],["branch"],["tree"],["entrance","door"],["building"],["gray","grey"]], 4),
 ("j_kid_ball",     "עקוב אחרי הילד עם הכדור שרץ ליד הגדר של המגרש שמאחורי בית הספר",
    "Track the kid with the ball running along the fence of the field behind the school",
    [["child","kid","boy"],["ball"],["run"],["fence"],["field","court","lot"],["behind"],["school"]], 4),
 ("j_win_gas",      "התמקד בחלון השבור בקומה השנייה של הבית שמול תחנת הדלק",
    "Focus on the broken window on the second floor of the house opposite the gas station",
    [["window"],["broken"],["second"],["floor","story","storey"],["house","home","building"],["opposite","facing","across","front"],["gas","fuel","petrol"],["station"]], 4),
 ("j_hat_bench",    "מצא את הכובע שנפל ליד הספסל שמתחת לעץ הגדול בפינת הפארק",
    "Find the hat that fell next to the bench under the big tree at the corner of the park",
    [["hat","cap"],["fell","fall","dropp"],["bench"],["under","beneath","below"],["tree"],["big","large"],["corner"],["park"]], 4),
 ("j_flag_mast",    "סמן את הדגל הקטן שעל התורן של הסירה שקשורה למזח הדרומי",
    "Mark the small flag on the mast of the boat tied to the southern pier",
    [["flag"],["small"],["mast","pole"],["boat"],["tie","moor","dock"],["south"],["pier","dock","jetty","wharf"]], 4),
 ("j_sticker",      "הדגש את המדבקה שעל הפגוש של המכונית שחונה מאחורי המשאית הירוקה",
    "Highlight the sticker on the bumper of the car parked behind the green truck",
    [["sticker","decal"],["bumper"],["car","vehicle"],["park"],["behind"],["green"],["truck","lorry"]], 4),
 ("j_dog_steps",    "עקוב אחרי הכלב הקטן שמשחק ליד הילדה שיושבת על המדרגות של הבית הלבן",
    "Track the small dog playing near the girl sitting on the steps of the white house",
    [["dog"],["small"],["play"],["girl","child"],["sit"],["stair","step"],["house","home"],["white"]], 4),
 ("j_lock_gate",    "התמקד במנעול שעל השער של הגדר שמקיפה את המגרש הריק",
    "Focus on the lock on the gate of the fence surrounding the empty lot",
    [["lock","padlock"],["gate"],["fence"],["surround","around","enclos"],["lot","field","yard"],["empty"]], 4),
 ("j_helmet_seat",  "מצא את הקסדה שמונחת על המושב של האופנוע שחונה ליד הכניסה לחניון",
    "Find the helmet on the seat of the motorcycle parked near the entrance of the parking garage",
    [["helmet"],["seat"],["motorcycle","motorbike"],["park"],["entrance"],["parking","garage"]], 4),
 ("j_sign_between", "סמן את השלט הקטן שמעל הדלת של החנות שבין המסעדה לבנק",
    "Mark the small sign above the door of the store between the restaurant and the bank",
    [["sign"],["small"],["above","over"],["door"],["store","shop"],["between"],["restaurant"],["bank"]], 4),
 ("j_drainpipe",    "הדגש את הצינור שיורד מהגג של הבית שליד עמוד החשמל הגבוה",
    "Highlight the drainpipe coming down from the roof of the house next to the tall pole",
    [["pipe","drain","gutter"],["roof"],["house","home","building"],["pole","post","pylon"],["tall","high"]], 4),
 ("j_umbrella_x",   "עקוב אחרי האישה עם המטרייה האדומה שחוצה את הכביש ליד הרמזור",
    "Track the woman with the red umbrella crossing the road near the traffic light",
    [["woman","lady"],["umbrella"],["red"],["cross"],["road","street"],["light","signal","crosswalk"]], 4),
 ("j_hole_wall",    "התמקד בחור שבקיר של המבנה הישן שמאחורי מגרש החניה",
    "Focus on the hole in the wall of the old structure behind the parking lot",
    [["hole","gap","opening"],["wall"],["old"],["building","structure"],["behind"],["parking"]], 4),
 ("j_tilt_sign",    "מצא את התמרור שנוטה הצידה ליד הפנייה לרחוב עם העצים",
    "Find the road sign leaning sideways near the turn to the street with the trees",
    [["sign"],["lean","tilt","bent"],["turn","junction","corner"],["tree"]], 4),
 ("j_crate_trunk",  "סמן את הארגז שמציץ מתא המטען של הרכב שחונה מול השער הצהוב",
    "Mark the crate sticking out of the trunk of the vehicle parked opposite the yellow gate",
    [["box","crate"],["trunk","boot","cargo"],["car","vehicle"],["park"],["opposite","facing","front","across"],["yellow"],["gate"]], 4),
 ("j_mural",        "הדגש את הציור שעל הקיר של הבניין שמימין לגשר להולכי הרגל",
    "Highlight the painting on the wall of the building to the right of the pedestrian bridge",
    [["paint","mural","graffiti","drawing"],["wall"],["building"],["right"],["pedestrian","foot"],["bridge"]], 4),
 ("j_cat_jump",     "עקוב אחרי החתול שקופץ מהגדר אל הגג של המחסן שבחצר האחורית",
    "Track the cat jumping from the fence onto the roof of the shed in the backyard",
    [["cat"],["jump","leap"],["fence"],["roof"],["shed","warehouse","storage"],["backyard","back yard"]], 4),
 ("j_faucet",       "התמקד בברז שבצד של הבית שליד הערוגה עם הפרחים האדומים",
    "Focus on the faucet on the side of the house next to the flowerbed with the red flowers",
    [["faucet","tap","spigot"],["side"],["house","home"],["flower"],["red"]], 4),
 ("j_truck_text",   "מצא את הכיתוב שעל הדופן של המשאית שעוצרת ליד תחנת האוטובוס המקורה",
    "Find the lettering on the side of the truck stopping near the covered bus stop",
    [["letter","text","writ","inscription"],["side"],["truck","lorry"],["bus"],["station","stop"],["cover","shelter","roof"]], 4),
 # -- 35 verbose pinpoint cases --
 ("j_pin_busstop",  "עקוב אחרי האיש עם החולצה הכחולה, זה שעומד ליד תחנת האוטובוס, בצד השמאלי של המסך, קרוב לספסל",
    "Track the man with the blue shirt, the one standing next to the bus station, on the left side of the frame, close to the bench",
    [["man","person"],["blue"],["shirt"],["stand"],["bus"],["station","stop"],["left"],["frame","screen","view","image"],["bench"]], 3),
 ("j_pin_notmoving","סמן את המכונית הלבנה, לא זו שנוסעת, זו שחונה ליד המדרכה, עם הדלת הפתוחה",
    "Mark the white car, not the one driving, the one parked next to the sidewalk, with the open door",
    [["car","vehicle"],["white"],["park"],["sidewalk","curb","pavement"],["door"],["open"]], 3),
 ("j_pin_antennas", "הדגש את הבניין הגבוה, זה עם האנטנות על הגג, שנמצא מאחורי מגרש המשחקים, קצת ימינה מהמרכז",
    "Highlight the tall building, the one with the antennas on the roof, behind the playground, slightly to the right of the center",
    [["building"],["tall","high"],["antenna"],["roof"],["behind"],["playground"],["right"],["center","middle"]], 3),
 ("j_pin_drone2",   "עקוב אחרי הרחפן השני, הקטן יותר, שטס נמוך מעל השדה, ליד קו העצים",
    "Track the second drone, the smaller one, flying low over the field, near the tree line",
    [["drone"],["second"],["small"],["fly"],["low"],["field"],["tree"]], 3),
 ("j_pin_leash",    "מצא את הכלב החום, עם הרצועה האדומה, שמשחק על הדשא, בין שני הספסלים, ליד השביל",
    "Find the brown dog, with the red leash, playing on the grass, between the two benches, near the path",
    [["dog"],["brown"],["leash"],["red"],["play"],["grass","lawn"],["between"],["bench"],["path","trail","walkway"]], 3),
 ("j_pin_window3",  "התמקד בחלון השלישי מימין, בקומה השנייה, של הבניין עם הקירות הצהובים, זה שליד בית הקפה",
    "Focus on the third window from the right, on the second floor, of the building with the yellow walls, the one next to the coffee shop",
    [["window"],["third"],["right"],["second"],["floor","story","storey"],["yellow"],["wall"],["coffee","cafe"]], 3),
 ("j_pin_notphone", "סמן את האדם שעומד הכי קרוב לכניסה, עם התיק הגדול, לא זה עם הטלפון",
    "Mark the person standing closest to the entrance, with the big bag, not the one with the phone",
    [["person","man"],["closest","nearest","close"],["entrance","door"],["bag","backpack"],["big","large"],["phone"]], 2),
 ("j_pin_2riders",  "עקוב אחרי האופנוע השחור, זה עם שני הרוכבים, שנוסע בנתיב הימני, לכיוון הצומת",
    "Track the black motorcycle, the one with the two riders, driving in the right lane, toward the intersection",
    [["motorcycle","motorbike"],["black"],["two"],["rider","passenger"],["right"],["lane"],["intersection","junction","crossroad"]], 3),
 ("j_pin_bluedoor", "הדגש את הדלת הכחולה, השלישית משמאל, בשורת החנויות, ליד הדוכן של הפירות",
    "Highlight the blue door, the third from the left, in the row of shops, next to the fruit stand",
    [["door"],["blue"],["third"],["left"],["row"],["shop","store"],["fruit"],["stand","stall","booth"]], 3),
 ("j_pin_smallbike","מצא את הילד עם הכובע האדום, זה שרוכב על אופניים קטנים, על השביל, ליד הברזייה",
    "Find the kid with the red cap, the one riding the small bicycle, on the path, near the drinking fountain",
    [["child","kid","boy"],["red"],["cap","hat"],["rid","cycl"],["bicycle","bike"],["small"],["path","trail"],["fountain"]], 3),
 ("j_pin_roofnear", "סמן את הגג של הבית הכי קרוב אליך, זה עם הסולם שנשען עליו",
    "Mark the roof of the house closest to you, the one with the ladder leaning on it",
    [["roof"],["house","home"],["closest","nearest","close"],["ladder"],["lean"]], 3),
 ("j_pin_leaving",  "עקוב אחרי המשאית הכתומה שיוצאת עכשיו מהאתר, זו עם הארגז הפתוח",
    "Track the orange truck leaving the site now, the one with the open box",
    [["truck","lorry"],["orange"],["leav","exit","pull"],["site"],["open"]], 3),
 ("j_pin_flagman",  "הדגש את האיש בקצה הימני של הקבוצה, זה עם הכובע, שמחזיק את הדגל",
    "Highlight the man at the right edge of the group, the one with the hat, holding the flag",
    [["man","person"],["right"],["edge","end"],["group"],["hat","cap"],["hold","carry"],["flag"]], 3),
 ("j_pin_notsail",  "התמקד בסירה הקטנה עם המנוע, לא במפרשית, זו שקרובה יותר לחוף",
    "Focus on the small boat with the motor, not the sailboat, the one closer to the shore",
    [["boat"],["small"],["motor","engine"],["sail"],["closer","nearer","close"],["shore","beach","coast"]], 2),
 ("j_pin_bushes",   "מצא את הפתח בגדר, בערך באמצע שלה, איפה שהשיחים נמוכים",
    "Find the gap in the fence, around the middle of it, where the bushes are low",
    [["gap","opening","hole","breach"],["fence"],["middle","halfway","center"],["bush","shrub"],["low","short"]], 3),
 ("j_pin_campole",  "סמן את העמוד עם המצלמה, זה שנמצא בפינה של החניון, ליד היציאה",
    "Mark the pole with the camera, the one at the corner of the parking lot, near the exit",
    [["pole","post"],["camera"],["corner"],["parking"],["exit"]], 3),
 ("j_pin_fastwalk", "עקוב אחרי האישה עם המעיל הארוך, זו שהולכת מהר, בצד הרחוק של הכיכר",
    "Track the woman with the long coat, the one walking fast, on the far side of the square",
    [["woman","lady"],["coat"],["long"],["walk"],["fast","quick","brisk"],["far"],["square","plaza"]], 3),
 ("j_pin_planks",   "הדגש את הערימה של הקרשים, ליד הקיר האחורי, מתחת לחלון",
    "Highlight the pile of wooden planks, near the back wall, under the window",
    [["pile","stack","heap"],["plank","wood","lumber","board"],["back","rear"],["wall"],["under","beneath","below"],["window"]], 3),
 ("j_pin_halfgate", "התמקד בשער הכחול בקצה השביל, זה שחצי פתוח",
    "Focus on the blue gate at the end of the path, the one that is half open",
    [["gate"],["blue"],["end","edge"],["path","trail"],["half"],["open"]], 2),
 ("j_pin_spare",    "מצא את הצמיג הרזרבי שמחובר לחלק האחורי של הגיפ האפור",
    "Find the spare tire attached to the back of the gray jeep",
    [["tire","tyre","wheel"],["spare"],["attach","mount","connect"],["back","rear"],["jeep","suv","vehicle"],["gray","grey"]], 3),
 ("j_pin_stage3",   "סמן את הקבוצה של שלושת האנשים שעומדים הכי קרוב לבמה, משמאל לרמקול הגדול",
    "Mark the group of three people standing closest to the stage, to the left of the big speaker",
    [["group"],["three"],["people"],["stand"],["closest","nearest","close"],["stage"],["left"],["speaker"]], 3),
 ("j_pin_hay",      "עקוב אחרי הטרקטור הירוק שעובד בשדה, זה שגורר את העגלה עם החציר",
    "Track the green tractor working in the field, the one towing the cart with the hay",
    [["tractor"],["green"],["field"],["tow","pull","haul"],["cart","trailer","wagon"],["hay","straw"]], 3),
 ("j_pin_fullbin",  "הדגש את הפח הכתום ליד הכניסה האחורית, זה שמלא עד למעלה",
    "Highlight the orange bin next to the back entrance, the one that is full to the top",
    [["bin","trash","garbage","dumpster"],["orange"],["back","rear"],["entrance","door"],["full"]], 3),
 ("j_pin_wirebirds","התמקד בציפורים שיושבות על החוטים, רק אלה שמעל הכביש, לא אלה שמעל המדרכה",
    "Focus on the birds sitting on the wires, only the ones above the road, not the ones above the sidewalk",
    [["bird"],["sit","perch"],["wire","cable","line"],["above","over"],["road","street"],["sidewalk","pavement","curb"]], 3),
 ("j_pin_extstairs","מצא את המדרגות החיצוניות בצד של הבניין, אלה שמובילות לגג",
    "Find the outdoor stairs on the side of the building, the ones leading to the roof",
    [["stair","step"],["side"],["building"],["lead"],["roof"]], 3),
 ("j_pin_wrongway", "סמן את הרכב היחיד בחניון שחונה הפוך, עם הפנים ליציאה",
    "Mark the only car in the parking lot parked the wrong way, facing the exit",
    [["car","vehicle"],["only","single"],["park"],["facing","front"],["exit"]], 3),
 ("j_pin_firstrun", "עקוב אחרי הקבוצה של הרצים, ספציפית אחרי זה עם האפוד הצהוב שרץ ראשון",
    "Track the group of runners, specifically the one with the yellow vest running first",
    [["run"],["yellow"],["vest"],["first","lead"]], 3),
 ("j_pin_barrel",   "הדגש את החבית שמונחת על הצד, ליד ערימת החול, מאחורי הבטונדות",
    "Highlight the barrel lying on its side, next to the pile of sand, behind the concrete barriers",
    [["barrel","drum"],["side","lying"],["sand"],["pile","heap","mound"],["behind"],["concrete","barrier","block"]], 3),
 ("j_pin_puddle",   "התמקד בשלולית הגדולה באמצע הדרך, זו שמשקפת את הבניין",
    "Focus on the big puddle in the middle of the road, the one reflecting the building",
    [["puddle","pool","water"],["big","large"],["middle","center"],["road","street","path"],["reflect"],["building"]], 3),
 ("j_pin_scaffold", "מצא את הסולם הכי גבוה בין אלה שנשענים על הפיגום, בצד המערבי",
    "Find the tallest ladder among the ones leaning on the scaffolding, on the west side",
    [["ladder"],["tall","high"],["lean"],["scaffold"],["west"]], 3),
 ("j_pin_idledozer","סמן את הדחפור הצהוב שעומד בלי לזוז ליד הבור הגדול, לא את זה שעובד",
    "Mark the yellow bulldozer standing still next to the big pit, not the one that is working",
    [["bulldozer","dozer","excavator"],["yellow"],["still","idle","stationary"],["pit","hole","excavation"],["big","large"]], 3),
 ("j_pin_cart",     "עקוב אחרי העגלה של הקניות שמישהו דוחף במעלה הרחוב, ליד המכוניות החונות",
    "Track the shopping cart someone is pushing up the street, near the parked cars",
    [["cart","trolley"],["shop"],["push"],["street","road"],["park"],["car","vehicle"]], 3),
 ("j_pin_graffiti", "הדגש את הכתובת שרשומה על הקיר, מתחת לחלון השני משמאל",
    "Highlight the writing on the wall, under the second window from the left",
    [["writ","graffiti","text","inscription"],["wall"],["under","beneath","below"],["second"],["window"],["left"]], 3),
 ("j_pin_ferris",   "התמקד בגלגל הענק בקצה הפארק, ספציפית בתא התחתון שלו",
    "Focus on the ferris wheel at the edge of the park, specifically its bottom cabin",
    [["wheel","ferris"],["park"],["edge","end"],["bottom","lowest","lower"],["cabin","car","gondola","pod"]], 3),
 ("j_pin_planters", "מצא את שני העציצים הגדולים משני צידי הדלת הראשית של המלון",
    "Find the two large planters on both sides of the main door of the hotel",
    [["two"],["planter","pot","plant"],["large","big"],["side"],["door","entrance"],["main"],["hotel"]], 3),
]

_refs_missing = [c[0] for c in INDIRECT_CASES if c[0] not in _REFS45]
assert not _refs_missing, f"missing refs: {_refs_missing}"
PERC100 = [(n, he, _REFS45[n], g, h) for n, he, g, h in INDIRECT_CASES] + _NEW55
assert len(PERC100) == 100 and len({c[0] for c in PERC100}) == 100

def check_refs():
    """Control calibration: every hand-written reference must satisfy its own groups."""
    from cases_perception import score_perception
    bad = [(n, ["|".join(g) for g in score_perception(en, groups)])
           for n, he, en, groups, h in PERC100 if score_perception(en, groups)]
    return bad
