"""The 100 multi-hop perception cases. These route to the VLM in the real system, so the
measured stage is translation; no planner ever sees them.
Case = (name, hebrew, english_reference, keyword_groups, depth).
english_reference is hand-written and is the control arm; check_refs() proves every reference
satisfies its own groups, so a control miss at runtime = scorer bug.
depth: 1 = attributed object, 2 = one reference link, 3 = two links, 4 = three chained links.
Scoring = keyword-group preservation: every group needs >=1 synonym as a lowercase substring of
the English output. Relation INVERSION is not machine-checked -- review the dump for that."""

PERC100 = [
 ('i_mid_windows', 'הדגש את החלונות האמצעיים של הבניין הימני ביותר', 'Highlight the middle windows of the rightmost building', [['highlight', 'mark'], ['window'], ['middle', 'center'], ['building'], ['right']], 2),
 ('i_third_door', 'סמן את הדלת הקדמית של הבית השלישי משמאל', 'Mark the front door of the third house from the left', [['door'], ['front'], ['house', 'home', 'building'], ['third'], ['left']], 2),
 ('i_rear_wheel', 'התמקד בגלגל האחורי של האופנוע החונה', 'Focus on the rear wheel of the parked motorcycle', [['wheel'], ['rear', 'back'], ['motorcycle', 'motorbike'], ['park']], 2),
 ('i_top_windows', 'ספור את החלונות בקומה העליונה של המגדל', 'Count the windows on the top floor of the tower', [['count', 'how many'], ['window'], ['top', 'upper'], ['floor', 'story', 'storey'], ['tower', 'building']], 3),
 ('i_roof_corner', 'סמן את הפינה השמאלית העליונה של הגג האדום', 'Mark the top left corner of the red roof', [['corner'], ['left'], ['top', 'upper'], ['roof'], ['red']], 3),
 ('i_chimney', 'הדגש את הארובה של הבית הנמוך ביותר ברחוב', 'Highlight the chimney of the lowest house on the street', [['chimney'], ['house', 'home'], ['low', 'short'], ['street', 'road']], 2),
 ('i_back_entrance', 'מצא את הכניסה האחורית של המחסן הגדול', 'Find the back entrance of the big warehouse', [['entrance', 'door'], ['back', 'rear'], ['warehouse', 'storage', 'shed'], ['big', 'large']], 2),
 ('i_ladder_pickup', 'סמן את הסולם שעל הגג של הטנדר הלבן', 'Mark the ladder on the roof of the white pickup', [['ladder'], ['roof'], ['pickup', 'van', 'truck'], ['white']], 3),
 ('i_car_by_red', 'הדגש את המכונית שצמודה לאדם עם הלבוש האדום', 'Highlight the car adjacent to the person with the red attire', [['car', 'vehicle'], ['next', 'adjacent', 'beside', 'near', 'close'], ['person', 'man'], ['red']], 2),
 ('i_orange_cap', 'עקוב אחרי האדם עם הכובע הכתום', 'Track the person with the orange cap', [['track', 'follow'], ['person', 'man'], ['orange'], ['cap', 'hat']], 1),
 ('i_door_by_coat', 'סמן את הדלת שליד האיש עם המעיל השחור', 'Mark the door next to the man with the black coat', [['door'], ['next', 'beside', 'near'], ['man', 'person'], ['black'], ['coat', 'jacket']], 3),
 ('i_bike_fence', 'התמקד באופניים שנשענים על הגדר של הבית הצהוב', 'Focus on the bicycle leaning on the fence of the yellow house', [['bicycle', 'bike'], ['lean'], ['fence'], ['house', 'home'], ['yellow']], 3),
 ('i_dog_by_dress', 'עקוב אחרי הכלב שהולך ליד האישה עם השמלה הלבנה', 'Track the dog walking beside the woman in the white dress', [['dog'], ['walk'], ['beside', 'next', 'near', 'with'], ['woman', 'lady'], ['white'], ['dress']], 3),
 ('i_kid_bag', 'הדגש את התיק שמחזיק הילד עם החולצה הירוקה', 'Highlight the bag that the child with the green shirt is holding', [['bag', 'backpack'], ['hold', 'carry'], ['child', 'kid', 'boy'], ['green'], ['shirt']], 3),
 ('i_tree_truck', 'סמן את העץ שמאחורי המשאית הצהובה', 'Mark the tree behind the yellow truck', [['tree'], ['behind'], ['truck', 'lorry'], ['yellow']], 2),
 ('i_win_over_door', 'מצא את החלון שמעל הדלת הכחולה', 'Find the window above the blue door', [['window'], ['above', 'over'], ['door'], ['blue']], 2),
 ('i_cars_by_flag', 'ספור את המכוניות שחונות מול הבניין עם הדגל', 'Count the cars parked in front of the building with the flag', [['count', 'how many'], ['car', 'vehicle'], ['park'], ['front', 'opposite', 'facing', 'across'], ['building'], ['flag']], 3),
 ('i_bench_trees', 'הדגש את הספסל שבין שני העצים הגבוהים', 'Highlight the bench between the two tall trees', [['bench'], ['between'], ['tree'], ['tall', 'high']], 2),
 ('i_behind_moto', 'עקוב אחרי הרכב שנוסע מאחורי האופנוע האדום', 'Track the vehicle driving behind the red motorcycle', [['car', 'vehicle'], ['driv', 'mov', 'travel'], ['behind'], ['motorcycle', 'motorbike'], ['red']], 3),
 ('i_man_on_roof', 'סמן את האיש שעומד על הגג של הבניין הלבן', 'Mark the man standing on the roof of the white building', [['man', 'person'], ['stand'], ['roof'], ['building'], ['white']], 3),
 ('i_box_by_man', 'הדגש את התיבה שליד האיש שעומד על הגג של הבניין הלבן', 'Highlight the box next to the man standing on the roof of the white building', [['box', 'crate', 'chest'], ['next', 'beside', 'near'], ['man', 'person'], ['stand'], ['roof'], ['building'], ['white']], 3),
 ('i_girl_balloon', 'עקוב אחרי הילדה עם הבלון שהולכת ליד האישה עם העגלה', 'Track the girl with the balloon walking near the woman with the stroller', [['girl', 'child'], ['balloon'], ['walk'], ['near', 'beside', 'next', 'with'], ['woman', 'lady'], ['stroller', 'cart', 'carriage', 'pram']], 3),
 ('i_car_between', 'סמן את המכונית החונה בין הטנדר הלבן למשאית האדומה', 'Mark the car parked between the white pickup and the red truck', [['car', 'vehicle'], ['park'], ['between'], ['white'], ['pickup', 'van'], ['red'], ['truck', 'lorry']], 3),
 ('i_door_by_tree', 'מצא את הדלת של הבית שמול העץ הגבוה ביותר', 'Find the door of the house facing the tallest tree', [['door'], ['house', 'home'], ['opposite', 'facing', 'front', 'across'], ['tree'], ['tall', 'high']], 3),
 ('i_sign_awning', 'התמקד בשלט שמעל הכניסה של החנות עם הסוכך הירוק', 'Focus on the sign above the entrance of the store with the green awning', [['sign'], ['above', 'over'], ['entrance', 'door'], ['store', 'shop'], ['green'], ['awning', 'canopy']], 3),
 ('i_front_tire', 'הדגש את הצמיג הקדמי של המכונית שחונה הכי קרוב לשער', 'Highlight the front tire of the car parked closest to the gate', [['tire', 'tyre', 'wheel'], ['front'], ['car', 'vehicle'], ['park'], ['closest', 'nearest', 'close'], ['gate']], 3),
 ('i_bench_fountain', 'ספור את האנשים שיושבים על הספסלים משמאל למזרקה', 'Count the people sitting on the benches to the left of the fountain', [['count', 'how many'], ['people'], ['sit'], ['bench'], ['left'], ['fountain']], 3),
 ('i_exit_gray', 'עקוב אחרי האדם שיצא מהדלת של הבניין האפור', 'Track the person who came out of the door of the gray building', [['person', 'man'], ['exit', 'left', 'came out', 'out of'], ['door'], ['building'], ['gray', 'grey']], 3),
 ('i_second_car', 'סמן את הרכב השני משמאל בשורה הקדמית של החניון', 'Mark the second vehicle from the left in the front row of the parking lot', [['car', 'vehicle'], ['second'], ['left'], ['front'], ['row'], ['parking']], 3),
 ('i_dark_stain', 'מצא את הכתם הכהה על הקיר שמימין לחלון הגדול', 'Find the dark stain on the wall to the right of the big window', [['stain', 'spot', 'mark', 'patch'], ['dark'], ['wall'], ['right'], ['window'], ['big', 'large']], 3),
 ('i_glasses_talk', 'הדגש את האיש עם המשקפיים שמדבר עם האישה בחולצה הצהובה', 'Highlight the man with the glasses talking to the woman in the yellow shirt', [['man', 'person'], ['glasses'], ['talk', 'speak', 'convers'], ['woman', 'lady'], ['yellow'], ['shirt']], 3),
 ('i_truck_boat', 'עקוב אחרי המשאית שגוררת את הסירה הלבנה', 'Track the truck towing the white boat', [['truck', 'lorry'], ['tow', 'pull', 'haul'], ['boat'], ['white']], 2),
 ('i_empty_chair', 'סמן את הכיסא הריק ליד השולחן העגול', 'Mark the empty chair next to the round table', [['chair'], ['empty'], ['next', 'beside', 'near'], ['table'], ['round']], 2),
 ('i_bird_cable', 'התמקד בציפור שיושבת על הכבל בין שני העמודים', 'Focus on the bird sitting on the cable between the two poles', [['bird'], ['sit'], ['cable', 'wire', 'line'], ['between'], ['pole', 'post', 'pillar']], 3),
 ('i_fence_gap', 'מצא את הפתח בגדר שמאחורי המכולה הכחולה', 'Find the opening in the fence behind the blue container', [['opening', 'gap', 'hole', 'breach'], ['fence'], ['behind'], ['container'], ['blue']], 3),
 ('i_main_steps', 'ספור את המדרגות בכניסה הראשית של הבניין הגבוה', 'Count the steps at the main entrance of the tall building', [['count', 'how many'], ['stair', 'step'], ['entrance'], ['main'], ['building'], ['tall', 'high']], 3),
 ('i_helmet_mid', 'הדגש את הרוכב עם הקסדה הצהובה שנמצא במרכז הקבוצה', 'Highlight the rider with the yellow helmet in the middle of the group', [['rider', 'cyclist'], ['helmet'], ['yellow'], ['middle', 'center'], ['group']], 3),
 ('i_cat_climb', 'עקוב אחרי החתול שמטפס על העץ שליד החומה', 'Track the cat climbing the tree next to the wall', [['cat'], ['climb'], ['tree'], ['next', 'beside', 'near'], ['wall']], 3),
 ('i_lean_silver', 'סמן את הבחור שנשען על המכונית הכסופה', 'Mark the guy leaning on the silver car', [['guy', 'man', 'person'], ['lean'], ['car', 'vehicle'], ['silver']], 2),
 ('i_flag_low', 'מצא את הדגל שמתנוסס מעל הגג של המבנה הנמוך', 'Find the flag flying above the roof of the low structure', [['flag'], ['fly', 'wav', 'hoist', 'flutter'], ['above', 'over'], ['roof'], ['building', 'structure'], ['low', 'short']], 3),
 ('i_broken_window', 'הדגש את החלון השבור בקומה התחתונה של הבניין הנטוש', 'Highlight the broken window on the bottom floor of the abandoned building', [['window'], ['broken'], ['bottom', 'lower', 'ground'], ['floor', 'story', 'storey'], ['building'], ['abandoned', 'deserted']], 3),
 ('i_last_convoy', 'עקוב אחרי המכונית האחרונה בשיירה', 'Track the last car in the convoy', [['car', 'vehicle'], ['last'], ['convoy', 'column', 'caravan', 'line']], 2),
 ('i_big_tent', 'סמן את האוהל הגדול ביותר בקצה השדה', 'Mark the biggest tent at the edge of the field', [['tent'], ['big', 'large'], ['edge', 'end'], ['field']], 2),
 ('i_crane_arm', 'התמקד בזרוע של המנוף שמעל אתר הבנייה', 'Focus on the arm of the crane above the construction site', [['arm', 'boom', 'jib'], ['crane'], ['above', 'over'], ['construction'], ['site']], 3),
 ('i_boats_pier', 'ספור את הסירות הקשורות למזח הצפוני', 'Count the boats tied to the northern pier', [['count', 'how many'], ['boat'], ['tie', 'moor'], ['north'], ['pier', 'dock', 'jetty', 'wharf']], 2),
 ('j_bag_chain', 'הדגש את התיק שמונח ליד הכיסא שמאחורי הדלפק של החנות עם הסוכך הכחול', 'Highlight the bag lying next to the chair behind the counter of the store with the blue awning', [['bag', 'backpack'], ['next', 'beside', 'near'], ['chair'], ['behind'], ['counter'], ['store', 'shop'], ['blue'], ['awning', 'canopy']], 4),
 ('j_bird_branch', 'סמן את הציפור שעל הענף של העץ שליד הכניסה לבניין האפור', 'Mark the bird on the branch of the tree next to the entrance of the gray building', [['bird'], ['branch'], ['tree'], ['entrance', 'door'], ['building'], ['gray', 'grey']], 4),
 ('j_kid_ball', 'עקוב אחרי הילד עם הכדור שרץ ליד הגדר של המגרש שמאחורי בית הספר', 'Track the kid with the ball running along the fence of the field behind the school', [['child', 'kid', 'boy'], ['ball'], ['run'], ['fence'], ['field', 'court', 'lot'], ['behind'], ['school']], 4),
 ('j_win_gas', 'התמקד בחלון השבור בקומה השנייה של הבית שמול תחנת הדלק', 'Focus on the broken window on the second floor of the house opposite the gas station', [['window'], ['broken'], ['second'], ['floor', 'story', 'storey'], ['house', 'home', 'building'], ['opposite', 'facing', 'across', 'front'], ['gas', 'fuel', 'petrol'], ['station']], 4),
 ('j_hat_bench', 'מצא את הכובע שנפל ליד הספסל שמתחת לעץ הגדול בפינת הפארק', 'Find the hat that fell next to the bench under the big tree at the corner of the park', [['hat', 'cap'], ['fell', 'fall', 'dropp'], ['bench'], ['under', 'beneath', 'below'], ['tree'], ['big', 'large'], ['corner'], ['park']], 4),
 ('j_flag_mast', 'סמן את הדגל הקטן שעל התורן של הסירה שקשורה למזח הדרומי', 'Mark the small flag on the mast of the boat tied to the southern pier', [['flag'], ['small'], ['mast', 'pole'], ['boat'], ['tie', 'moor', 'dock'], ['south'], ['pier', 'dock', 'jetty', 'wharf']], 4),
 ('j_sticker', 'הדגש את המדבקה שעל הפגוש של המכונית שחונה מאחורי המשאית הירוקה', 'Highlight the sticker on the bumper of the car parked behind the green truck', [['sticker', 'decal'], ['bumper'], ['car', 'vehicle'], ['park'], ['behind'], ['green'], ['truck', 'lorry']], 4),
 ('j_dog_steps', 'עקוב אחרי הכלב הקטן שמשחק ליד הילדה שיושבת על המדרגות של הבית הלבן', 'Track the small dog playing near the girl sitting on the steps of the white house', [['dog'], ['small'], ['play'], ['girl', 'child'], ['sit'], ['stair', 'step'], ['house', 'home'], ['white']], 4),
 ('j_lock_gate', 'התמקד במנעול שעל השער של הגדר שמקיפה את המגרש הריק', 'Focus on the lock on the gate of the fence surrounding the empty lot', [['lock', 'padlock'], ['gate'], ['fence'], ['surround', 'around', 'enclos'], ['lot', 'field', 'yard'], ['empty']], 4),
 ('j_helmet_seat', 'מצא את הקסדה שמונחת על המושב של האופנוע שחונה ליד הכניסה לחניון', 'Find the helmet on the seat of the motorcycle parked near the entrance of the parking garage', [['helmet'], ['seat'], ['motorcycle', 'motorbike'], ['park'], ['entrance'], ['parking', 'garage']], 4),
 ('j_sign_between', 'סמן את השלט הקטן שמעל הדלת של החנות שבין המסעדה לבנק', 'Mark the small sign above the door of the store between the restaurant and the bank', [['sign'], ['small'], ['above', 'over'], ['door'], ['store', 'shop'], ['between'], ['restaurant'], ['bank']], 4),
 ('j_drainpipe', 'הדגש את הצינור שיורד מהגג של הבית שליד עמוד החשמל הגבוה', 'Highlight the drainpipe coming down from the roof of the house next to the tall pole', [['pipe', 'drain', 'gutter'], ['roof'], ['house', 'home', 'building'], ['pole', 'post', 'pylon'], ['tall', 'high']], 4),
 ('j_umbrella_x', 'עקוב אחרי האישה עם המטרייה האדומה שחוצה את הכביש ליד הרמזור', 'Track the woman with the red umbrella crossing the road near the traffic light', [['woman', 'lady'], ['umbrella'], ['red'], ['cross'], ['road', 'street'], ['light', 'signal', 'crosswalk']], 4),
 ('j_hole_wall', 'התמקד בחור שבקיר של המבנה הישן שמאחורי מגרש החניה', 'Focus on the hole in the wall of the old structure behind the parking lot', [['hole', 'gap', 'opening'], ['wall'], ['old'], ['building', 'structure'], ['behind'], ['parking']], 4),
 ('j_tilt_sign', 'מצא את התמרור שנוטה הצידה ליד הפנייה לרחוב עם העצים', 'Find the road sign leaning sideways near the turn to the street with the trees', [['sign'], ['lean', 'tilt', 'bent'], ['turn', 'junction', 'corner'], ['tree']], 4),
 ('j_crate_trunk', 'סמן את הארגז שמציץ מתא המטען של הרכב שחונה מול השער הצהוב', 'Mark the crate sticking out of the trunk of the vehicle parked opposite the yellow gate', [['box', 'crate'], ['trunk', 'boot', 'cargo'], ['car', 'vehicle'], ['park'], ['opposite', 'facing', 'front', 'across'], ['yellow'], ['gate']], 4),
 ('j_mural', 'הדגש את הציור שעל הקיר של הבניין שמימין לגשר להולכי הרגל', 'Highlight the painting on the wall of the building to the right of the pedestrian bridge', [['paint', 'mural', 'graffiti', 'drawing'], ['wall'], ['building'], ['right'], ['pedestrian', 'foot'], ['bridge']], 4),
 ('j_cat_jump', 'עקוב אחרי החתול שקופץ מהגדר אל הגג של המחסן שבחצר האחורית', 'Track the cat jumping from the fence onto the roof of the shed in the backyard', [['cat'], ['jump', 'leap'], ['fence'], ['roof'], ['shed', 'warehouse', 'storage'], ['backyard', 'back yard']], 4),
 ('j_faucet', 'התמקד בברז שבצד של הבית שליד הערוגה עם הפרחים האדומים', 'Focus on the faucet on the side of the house next to the flowerbed with the red flowers', [['faucet', 'tap', 'spigot'], ['side'], ['house', 'home'], ['flower'], ['red']], 4),
 ('j_truck_text', 'מצא את הכיתוב שעל הדופן של המשאית שעוצרת ליד תחנת האוטובוס המקורה', 'Find the lettering on the side of the truck stopping near the covered bus stop', [['letter', 'text', 'writ', 'inscription'], ['side'], ['truck', 'lorry'], ['bus'], ['station', 'stop'], ['cover', 'shelter', 'roof']], 4),
 ('j_pin_busstop', 'עקוב אחרי האיש עם החולצה הכחולה, זה שעומד ליד תחנת האוטובוס, בצד השמאלי של המסך, קרוב לספסל', 'Track the man with the blue shirt, the one standing next to the bus station, on the left side of the frame, close to the bench', [['man', 'person'], ['blue'], ['shirt'], ['stand'], ['bus'], ['station', 'stop'], ['left'], ['frame', 'screen', 'view', 'image'], ['bench']], 3),
 ('j_pin_notmoving', 'סמן את המכונית הלבנה, לא זו שנוסעת, זו שחונה ליד המדרכה, עם הדלת הפתוחה', 'Mark the white car, not the one driving, the one parked next to the sidewalk, with the open door', [['car', 'vehicle'], ['white'], ['park'], ['sidewalk', 'curb', 'pavement'], ['door'], ['open']], 3),
 ('j_pin_antennas', 'הדגש את הבניין הגבוה, זה עם האנטנות על הגג, שנמצא מאחורי מגרש המשחקים, קצת ימינה מהמרכז', 'Highlight the tall building, the one with the antennas on the roof, behind the playground, slightly to the right of the center', [['building'], ['tall', 'high'], ['antenna'], ['roof'], ['behind'], ['playground'], ['right'], ['center', 'middle']], 3),
 ('j_pin_drone2', 'עקוב אחרי הרחפן השני, הקטן יותר, שטס נמוך מעל השדה, ליד קו העצים', 'Track the second drone, the smaller one, flying low over the field, near the tree line', [['drone'], ['second'], ['small'], ['fly'], ['low'], ['field'], ['tree']], 3),
 ('j_pin_leash', 'מצא את הכלב החום, עם הרצועה האדומה, שמשחק על הדשא, בין שני הספסלים, ליד השביל', 'Find the brown dog, with the red leash, playing on the grass, between the two benches, near the path', [['dog'], ['brown'], ['leash'], ['red'], ['play'], ['grass', 'lawn'], ['between'], ['bench'], ['path', 'trail', 'walkway']], 3),
 ('j_pin_window3', 'התמקד בחלון השלישי מימין, בקומה השנייה, של הבניין עם הקירות הצהובים, זה שליד בית הקפה', 'Focus on the third window from the right, on the second floor, of the building with the yellow walls, the one next to the coffee shop', [['window'], ['third'], ['right'], ['second'], ['floor', 'story', 'storey'], ['yellow'], ['wall'], ['coffee', 'cafe']], 3),
 ('j_pin_notphone', 'סמן את האדם שעומד הכי קרוב לכניסה, עם התיק הגדול, לא זה עם הטלפון', 'Mark the person standing closest to the entrance, with the big bag, not the one with the phone', [['person', 'man'], ['closest', 'nearest', 'close'], ['entrance', 'door'], ['bag', 'backpack'], ['big', 'large'], ['phone']], 2),
 ('j_pin_2riders', 'עקוב אחרי האופנוע השחור, זה עם שני הרוכבים, שנוסע בנתיב הימני, לכיוון הצומת', 'Track the black motorcycle, the one with the two riders, driving in the right lane, toward the intersection', [['motorcycle', 'motorbike'], ['black'], ['two'], ['rider', 'passenger'], ['right'], ['lane'], ['intersection', 'junction', 'crossroad']], 3),
 ('j_pin_bluedoor', 'הדגש את הדלת הכחולה, השלישית משמאל, בשורת החנויות, ליד הדוכן של הפירות', 'Highlight the blue door, the third from the left, in the row of shops, next to the fruit stand', [['door'], ['blue'], ['third'], ['left'], ['row'], ['shop', 'store'], ['fruit'], ['stand', 'stall', 'booth']], 3),
 ('j_pin_smallbike', 'מצא את הילד עם הכובע האדום, זה שרוכב על אופניים קטנים, על השביל, ליד הברזייה', 'Find the kid with the red cap, the one riding the small bicycle, on the path, near the drinking fountain', [['child', 'kid', 'boy'], ['red'], ['cap', 'hat'], ['rid', 'cycl'], ['bicycle', 'bike'], ['small'], ['path', 'trail'], ['fountain']], 3),
 ('j_pin_roofnear', 'סמן את הגג של הבית הכי קרוב אליך, זה עם הסולם שנשען עליו', 'Mark the roof of the house closest to you, the one with the ladder leaning on it', [['roof'], ['house', 'home'], ['closest', 'nearest', 'close'], ['ladder'], ['lean']], 3),
 ('j_pin_leaving', 'עקוב אחרי המשאית הכתומה שיוצאת עכשיו מהאתר, זו עם הארגז הפתוח', 'Track the orange truck leaving the site now, the one with the open box', [['truck', 'lorry'], ['orange'], ['leav', 'exit', 'pull'], ['site'], ['open']], 3),
 ('j_pin_flagman', 'הדגש את האיש בקצה הימני של הקבוצה, זה עם הכובע, שמחזיק את הדגל', 'Highlight the man at the right edge of the group, the one with the hat, holding the flag', [['man', 'person'], ['right'], ['edge', 'end'], ['group'], ['hat', 'cap'], ['hold', 'carry'], ['flag']], 3),
 ('j_pin_notsail', 'התמקד בסירה הקטנה עם המנוע, לא במפרשית, זו שקרובה יותר לחוף', 'Focus on the small boat with the motor, not the sailboat, the one closer to the shore', [['boat'], ['small'], ['motor', 'engine'], ['sail'], ['closer', 'nearer', 'close'], ['shore', 'beach', 'coast']], 2),
 ('j_pin_bushes', 'מצא את הפתח בגדר, בערך באמצע שלה, איפה שהשיחים נמוכים', 'Find the gap in the fence, around the middle of it, where the bushes are low', [['gap', 'opening', 'hole', 'breach'], ['fence'], ['middle', 'halfway', 'center'], ['bush', 'shrub'], ['low', 'short']], 3),
 ('j_pin_campole', 'סמן את העמוד עם המצלמה, זה שנמצא בפינה של החניון, ליד היציאה', 'Mark the pole with the camera, the one at the corner of the parking lot, near the exit', [['pole', 'post'], ['camera'], ['corner'], ['parking'], ['exit']], 3),
 ('j_pin_fastwalk', 'עקוב אחרי האישה עם המעיל הארוך, זו שהולכת מהר, בצד הרחוק של הכיכר', 'Track the woman with the long coat, the one walking fast, on the far side of the square', [['woman', 'lady'], ['coat'], ['long'], ['walk'], ['fast', 'quick', 'brisk'], ['far'], ['square', 'plaza']], 3),
 ('j_pin_planks', 'הדגש את הערימה של הקרשים, ליד הקיר האחורי, מתחת לחלון', 'Highlight the pile of wooden planks, near the back wall, under the window', [['pile', 'stack', 'heap'], ['plank', 'wood', 'lumber', 'board'], ['back', 'rear'], ['wall'], ['under', 'beneath', 'below'], ['window']], 3),
 ('j_pin_halfgate', 'התמקד בשער הכחול בקצה השביל, זה שחצי פתוח', 'Focus on the blue gate at the end of the path, the one that is half open', [['gate'], ['blue'], ['end', 'edge'], ['path', 'trail'], ['half'], ['open']], 2),
 ('j_pin_spare', 'מצא את הצמיג הרזרבי שמחובר לחלק האחורי של הגיפ האפור', 'Find the spare tire attached to the back of the gray jeep', [['tire', 'tyre', 'wheel'], ['spare'], ['attach', 'mount', 'connect'], ['back', 'rear'], ['jeep', 'suv', 'vehicle'], ['gray', 'grey']], 3),
 ('j_pin_stage3', 'סמן את הקבוצה של שלושת האנשים שעומדים הכי קרוב לבמה, משמאל לרמקול הגדול', 'Mark the group of three people standing closest to the stage, to the left of the big speaker', [['group'], ['three'], ['people'], ['stand'], ['closest', 'nearest', 'close'], ['stage'], ['left'], ['speaker']], 3),
 ('j_pin_hay', 'עקוב אחרי הטרקטור הירוק שעובד בשדה, זה שגורר את העגלה עם החציר', 'Track the green tractor working in the field, the one towing the cart with the hay', [['tractor'], ['green'], ['field'], ['tow', 'pull', 'haul'], ['cart', 'trailer', 'wagon'], ['hay', 'straw']], 3),
 ('j_pin_fullbin', 'הדגש את הפח הכתום ליד הכניסה האחורית, זה שמלא עד למעלה', 'Highlight the orange bin next to the back entrance, the one that is full to the top', [['bin', 'trash', 'garbage', 'dumpster'], ['orange'], ['back', 'rear'], ['entrance', 'door'], ['full']], 3),
 ('j_pin_wirebirds', 'התמקד בציפורים שיושבות על החוטים, רק אלה שמעל הכביש, לא אלה שמעל המדרכה', 'Focus on the birds sitting on the wires, only the ones above the road, not the ones above the sidewalk', [['bird'], ['sit', 'perch'], ['wire', 'cable', 'line'], ['above', 'over'], ['road', 'street'], ['sidewalk', 'pavement', 'curb']], 3),
 ('j_pin_extstairs', 'מצא את המדרגות החיצוניות בצד של הבניין, אלה שמובילות לגג', 'Find the outdoor stairs on the side of the building, the ones leading to the roof', [['stair', 'step'], ['side'], ['building'], ['lead'], ['roof']], 3),
 ('j_pin_wrongway', 'סמן את הרכב היחיד בחניון שחונה הפוך, עם הפנים ליציאה', 'Mark the only car in the parking lot parked the wrong way, facing the exit', [['car', 'vehicle'], ['only', 'single'], ['park'], ['facing', 'front'], ['exit']], 3),
 ('j_pin_firstrun', 'עקוב אחרי הקבוצה של הרצים, ספציפית אחרי זה עם האפוד הצהוב שרץ ראשון', 'Track the group of runners, specifically the one with the yellow vest running first', [['run'], ['yellow'], ['vest'], ['first', 'lead']], 3),
 ('j_pin_barrel', 'הדגש את החבית שמונחת על הצד, ליד ערימת החול, מאחורי הבטונדות', 'Highlight the barrel lying on its side, next to the pile of sand, behind the concrete barriers', [['barrel', 'drum'], ['side', 'lying'], ['sand'], ['pile', 'heap', 'mound'], ['behind'], ['concrete', 'barrier', 'block']], 3),
 ('j_pin_puddle', 'התמקד בשלולית הגדולה באמצע הדרך, זו שמשקפת את הבניין', 'Focus on the big puddle in the middle of the road, the one reflecting the building', [['puddle', 'pool', 'water'], ['big', 'large'], ['middle', 'center'], ['road', 'street', 'path'], ['reflect'], ['building']], 3),
 ('j_pin_scaffold', 'מצא את הסולם הכי גבוה בין אלה שנשענים על הפיגום, בצד המערבי', 'Find the tallest ladder among the ones leaning on the scaffolding, on the west side', [['ladder'], ['tall', 'high'], ['lean'], ['scaffold'], ['west']], 3),
 ('j_pin_idledozer', 'סמן את הדחפור הצהוב שעומד בלי לזוז ליד הבור הגדול, לא את זה שעובד', 'Mark the yellow bulldozer standing still next to the big pit, not the one that is working', [['bulldozer', 'dozer', 'excavator'], ['yellow'], ['still', 'idle', 'stationary'], ['pit', 'hole', 'excavation'], ['big', 'large']], 3),
 ('j_pin_cart', 'עקוב אחרי העגלה של הקניות שמישהו דוחף במעלה הרחוב, ליד המכוניות החונות', 'Track the shopping cart someone is pushing up the street, near the parked cars', [['cart', 'trolley'], ['shop'], ['push'], ['street', 'road'], ['park'], ['car', 'vehicle']], 3),
 ('j_pin_graffiti', 'הדגש את הכתובת שרשומה על הקיר, מתחת לחלון השני משמאל', 'Highlight the writing on the wall, under the second window from the left', [['writ', 'graffiti', 'text', 'inscription'], ['wall'], ['under', 'beneath', 'below'], ['second'], ['window'], ['left']], 3),
 ('j_pin_ferris', 'התמקד בגלגל הענק בקצה הפארק, ספציפית בתא התחתון שלו', 'Focus on the ferris wheel at the edge of the park, specifically its bottom cabin', [['wheel', 'ferris'], ['park'], ['edge', 'end'], ['bottom', 'lowest', 'lower'], ['cabin', 'car', 'gondola', 'pod']], 3),
 ('j_pin_planters', 'מצא את שני העציצים הגדולים משני צידי הדלת הראשית של המלון', 'Find the two large planters on both sides of the main door of the hotel', [['two'], ['planter', 'pot', 'plant'], ['large', 'big'], ['side'], ['door', 'entrance'], ['main'], ['hotel']], 3),
]
assert len(PERC100) == 100 and len({c[0] for c in PERC100}) == 100

def score_perception(translation, groups):
    t = (translation or "").lower()
    return [g for g in groups if not any(s in t for s in g)]

def check_refs():
    return [(n, ["|".join(g) for g in score_perception(en, groups)])
            for n, he, en, groups, tag in PERC100 + SLANG20 if score_perception(en, groups)]


# 20 military-phraseology probes (owner request 2026-09-02). Register-robustness only: does the
# TRANSLATION stage survive IDF-style phrasing? Domain kept to observation/maneuver/report tasks.
# Class "idiom" = compositional slang and milspeak with real English equivalents -- prediction:
# translators survive it literally, the idiom->action mapping is the planner's job (glossary).
# Class "acronym" = acronyms, radio-procedure words, and their homographs -- prediction: breaks.
# Format: (name, hebrew, english_reference, keyword_groups, klass).
SLANG20 = [
 ("s_indian_circle", "תבצע מעגל אינדיאני על המטרה מולך",
    "Perform an Indian circle around the target in front of you",
    [["circle"],["target"],["front"]], "idiom"),
 ("s_sitrep",        "טפס לגובה ותן לי תמונת מצב",
    "Climb to altitude and give me a situation picture",
    [["climb"],["altitude","height","up"],["situation","status","picture"]], "idiom"),
 ("s_jump_point",    "קפוץ לנקודה ותשאר עליה",
    "Jump to the point and stay on it",
    [["point"],["stay","hold","remain"]], "idiom"),
 ("s_gentle_scan",   "תעשה לי סריקה עדינה על הגזרה",
    "Do a gentle scan over the sector",
    [["scan"],["sector","zone","area"]], "idiom"),
 ("s_eye_junction",  "שים עין על הצומת ואל תרד ממנו",
    "Keep an eye on the junction and do not come off it",
    [["eye","watch","monitor","observe"],["junction","intersection","crossroad"]], "idiom"),
 ("s_zoom_suspect",  "תן זום על הרכב החשוד ותחזיק אותו במרכז",
    "Zoom in on the suspicious vehicle and hold it in the center",
    [["zoom"],["vehicle","car"],["suspicious","suspect"],["center","middle"]], "idiom"),
 ("s_route_escort",  "עלה על ציר התנועה ותלווה אותו עד הפנייה",
    "Get on the movement route and follow it until the turn",
    [["route","axis","road"],["follow","escort","accompany"],["turn"]], "idiom"),
 ("s_dead_ground",   "תפוס גובה, יש לך שטח מת מאחורי הגבעה",
    "Gain altitude, you have dead ground behind the hill",
    [["altitude","height","climb"],["dead"],["behind"],["hill"]], "idiom"),
 ("s_give_distance", "רחפן שני נכנס לגזרה שלך, תן לו מרחק",
    "A second drone is entering your sector, give it distance",
    [["drone"],["second"],["sector","zone","area"],["distance","space","room"]], "idiom"),
 ("s_one_more_pass", "תעשה עוד סיבוב מעל השכונה ואז תחזור הביתה",
    "Do one more pass over the neighborhood and then come back home",
    [["pass","circle","round","loop","turn"],["neighborhood"],["home","back","return"]], "idiom"),
 ("s_grid_out",      "עבור לנ.צ. שנתתי לך, סוף",
    "Proceed to the grid reference I gave you, out",
    [["grid","coordinates","reference","waypoint"],["out","over","end"]], "acronym"),
 ("s_roger_over",    "רות, ממשיך בסריקה, עבור",
    "Roger, continuing the scan, over",
    [["roger","copy","acknowledged"],["continu"],["scan"],["over"]], "acronym"),
 ("s_cp_visual",     "יש לי קשר עין עם החפ\"ק ליד המבנה",
    "I have eye contact with the command post near the structure",
    [["eye","visual","sight"],["command","post","headquarters"],["building","structure"]], "acronym"),
 ("s_eyes_on",       "תדווח כשיש לך עיניים על המטרה",
    "Report when you have eyes on the target",
    [["report"],["eyes"],["target"]], "acronym"),
 ("s_rally_point",   "קיבלתי, חוזר לנק' האיסוף",
    "Roger, returning to the collection point",
    [["roger","received","copy","got"],["return"],["point"],["collect","assembly","pickup","rally"]], "acronym"),
 ("s_feet_hold",     "תעלה לשמונה מאות רגל ותחכה בהמתנה מעל האזור",
    "Climb to eight hundred feet and hold over the area",
    [["eight hundred","800"],["feet","ft"],["hold","wait","loiter"],["area","zone"]], "acronym"),
 ("s_lost_uav",      "אבד קשר עם הכטב\"ם, תתחיל סריקה בגזרה הצפונית",
    "Contact with the UAV was lost, start scanning in the northern sector",
    [["lost","no contact"],["uav","drone","unmanned","aircraft"],["scan"],["north"],["sector","zone","area"]], "acronym"),
 ("s_scramble",      "המראה מיידית, יש הקפצה",
    "Immediate takeoff, there is a scramble",
    [["takeoff","take off"],["immediate"],["scramble","alert","emergency"]], "acronym"),
 ("s_obs_report",    "החזק תצפית על הבית הלבן, דווח כל תזוזה, עבור",
    "Maintain observation on the white house, report any movement, over",
    [["observ","watch","surveill"],["house"],["white"],["report"],["movement","motion"],["over"]], "acronym"),
 ("s_wadi_route",    "טוס נמוך על הוואדי עד המפגש עם הציר, שם תמתין",
    "Fly low along the wadi until it meets the route, and wait there",
    [["low"],["wadi","valley","ravine","riverbed"],["route","axis","road"],["wait","hold"]], "acronym"),
]
assert len(SLANG20) == 20 and len({c[0] for c in SLANG20}) == 20
