"""45 hand-authored multi-hop perception commands (round 5). Each case: the target is reached
through attribute + relation links, not named directly. hops = reference depth: 1 = attributed
object, 2 = one link (part-of / next-to / behind...), 3 = two chained links.
The owner's three seed examples are i_mid_windows, i_orange_cap, i_car_by_red.
Format: (name, hebrew, keyword_groups, hops). Scored with score_perception (keyword presence);
relation INVERSION is not machine-checked -- the dump table is the ground truth for that."""
INDIRECT_CASES = [
 # -- part-of / superlative chains --
 ("i_mid_windows",  "הדגש את החלונות האמצעיים של הבניין הימני ביותר",
    [["highlight","mark"],["window"],["middle","center"],["building"],["right"]], 2),
 ("i_third_door",   "סמן את הדלת הקדמית של הבית השלישי משמאל",
    [["door"],["front"],["house","home","building"],["third"],["left"]], 2),
 ("i_rear_wheel",   "התמקד בגלגל האחורי של האופנוע החונה",
    [["wheel"],["rear","back"],["motorcycle","motorbike"],["park"]], 2),
 ("i_top_windows",  "ספור את החלונות בקומה העליונה של המגדל",
    [["count","how many"],["window"],["top","upper"],["floor","story","storey"],["tower","building"]], 3),
 ("i_roof_corner",  "סמן את הפינה השמאלית העליונה של הגג האדום",
    [["corner"],["left"],["top","upper"],["roof"],["red"]], 3),
 ("i_chimney",      "הדגש את הארובה של הבית הנמוך ביותר ברחוב",
    [["chimney"],["house","home"],["low","short"],["street","road"]], 2),
 ("i_back_entrance","מצא את הכניסה האחורית של המחסן הגדול",
    [["entrance","door"],["back","rear"],["warehouse","storage","shed"],["big","large"]], 2),
 ("i_ladder_pickup","סמן את הסולם שעל הגג של הטנדר הלבן",
    [["ladder"],["roof"],["pickup","van","truck"],["white"]], 3),
 # -- relation to an attributed entity (the owner's example class) --
 ("i_car_by_red",   "הדגש את המכונית שצמודה לאדם עם הלבוש האדום",
    [["car","vehicle"],["next","adjacent","beside","near","close"],["person","man"],["red"]], 2),
 ("i_orange_cap",   "עקוב אחרי האדם עם הכובע הכתום",
    [["track","follow"],["person","man"],["orange"],["cap","hat"]], 1),
 ("i_door_by_coat", "סמן את הדלת שליד האיש עם המעיל השחור",
    [["door"],["next","beside","near"],["man","person"],["black"],["coat","jacket"]], 3),
 ("i_bike_fence",   "התמקד באופניים שנשענים על הגדר של הבית הצהוב",
    [["bicycle","bike"],["lean"],["fence"],["house","home"],["yellow"]], 3),
 ("i_dog_by_dress", "עקוב אחרי הכלב שהולך ליד האישה עם השמלה הלבנה",
    [["dog"],["walk"],["beside","next","near","with"],["woman","lady"],["white"],["dress"]], 3),
 ("i_kid_bag",      "הדגש את התיק שמחזיק הילד עם החולצה הירוקה",
    [["bag","backpack"],["hold","carry"],["child","kid","boy"],["green"],["shirt"]], 3),
 ("i_tree_truck",   "סמן את העץ שמאחורי המשאית הצהובה",
    [["tree"],["behind"],["truck","lorry"],["yellow"]], 2),
 ("i_win_over_door","מצא את החלון שמעל הדלת הכחולה",
    [["window"],["above","over"],["door"],["blue"]], 2),
 ("i_cars_by_flag", "ספור את המכוניות שחונות מול הבניין עם הדגל",
    [["count","how many"],["car","vehicle"],["park"],["front","opposite","facing","across"],["building"],["flag"]], 3),
 ("i_bench_trees",  "הדגש את הספסל שבין שני העצים הגבוהים",
    [["bench"],["between"],["tree"],["tall","high"]], 2),
 ("i_behind_moto",  "עקוב אחרי הרכב שנוסע מאחורי האופנוע האדום",
    [["car","vehicle"],["driv","mov","travel"],["behind"],["motorcycle","motorbike"],["red"]], 3),
 ("i_man_on_roof",  "סמן את האיש שעומד על הגג של הבניין הלבן",
    [["man","person"],["stand"],["roof"],["building"],["white"]], 3),
 # -- two chained links and harder --
 ("i_box_by_man",   "הדגש את התיבה שליד האיש שעומד על הגג של הבניין הלבן",
    [["box","crate","chest"],["next","beside","near"],["man","person"],["stand"],["roof"],["building"],["white"]], 3),
 ("i_girl_balloon", "עקוב אחרי הילדה עם הבלון שהולכת ליד האישה עם העגלה",
    [["girl","child"],["balloon"],["walk"],["near","beside","next","with"],["woman","lady"],["stroller","cart","carriage","pram"]], 3),
 ("i_car_between",  "סמן את המכונית החונה בין הטנדר הלבן למשאית האדומה",
    [["car","vehicle"],["park"],["between"],["white"],["pickup","van"],["red"],["truck","lorry"]], 3),
 ("i_door_by_tree", "מצא את הדלת של הבית שמול העץ הגבוה ביותר",
    [["door"],["house","home"],["opposite","facing","front","across"],["tree"],["tall","high"]], 3),
 ("i_sign_awning",  "התמקד בשלט שמעל הכניסה של החנות עם הסוכך הירוק",
    [["sign"],["above","over"],["entrance","door"],["store","shop"],["green"],["awning","canopy"]], 3),
 ("i_front_tire",   "הדגש את הצמיג הקדמי של המכונית שחונה הכי קרוב לשער",
    [["tire","tyre","wheel"],["front"],["car","vehicle"],["park"],["closest","nearest","close"],["gate"]], 3),
 ("i_bench_fountain","ספור את האנשים שיושבים על הספסלים משמאל למזרקה",
    [["count","how many"],["people"],["sit"],["bench"],["left"],["fountain"]], 3),
 ("i_exit_gray",    "עקוב אחרי האדם שיצא מהדלת של הבניין האפור",
    [["person","man"],["exit","left","came out","out of"],["door"],["building"],["gray","grey"]], 3),
 ("i_second_car",   "סמן את הרכב השני משמאל בשורה הקדמית של החניון",
    [["car","vehicle"],["second"],["left"],["front"],["row"],["parking"]], 3),
 ("i_dark_stain",   "מצא את הכתם הכהה על הקיר שמימין לחלון הגדול",
    [["stain","spot","mark","patch"],["dark"],["wall"],["right"],["window"],["big","large"]], 3),
 ("i_glasses_talk", "הדגש את האיש עם המשקפיים שמדבר עם האישה בחולצה הצהובה",
    [["man","person"],["glasses"],["talk","speak","convers"],["woman","lady"],["yellow"],["shirt"]], 3),
 ("i_truck_boat",   "עקוב אחרי המשאית שגוררת את הסירה הלבנה",
    [["truck","lorry"],["tow","pull","haul"],["boat"],["white"]], 2),
 ("i_empty_chair",  "סמן את הכיסא הריק ליד השולחן העגול",
    [["chair"],["empty"],["next","beside","near"],["table"],["round"]], 2),
 ("i_bird_cable",   "התמקד בציפור שיושבת על הכבל בין שני העמודים",
    [["bird"],["sit"],["cable","wire","line"],["between"],["pole","post","pillar"]], 3),
 ("i_fence_gap",    "מצא את הפתח בגדר שמאחורי המכולה הכחולה",
    [["opening","gap","hole","breach"],["fence"],["behind"],["container"],["blue"]], 3),
 ("i_main_steps",   "ספור את המדרגות בכניסה הראשית של הבניין הגבוה",
    [["count","how many"],["stair","step"],["entrance"],["main"],["building"],["tall","high"]], 3),
 ("i_helmet_mid",   "הדגש את הרוכב עם הקסדה הצהובה שנמצא במרכז הקבוצה",
    [["rider","cyclist"],["helmet"],["yellow"],["middle","center"],["group"]], 3),
 ("i_cat_climb",    "עקוב אחרי החתול שמטפס על העץ שליד החומה",
    [["cat"],["climb"],["tree"],["next","beside","near"],["wall"]], 3),
 ("i_lean_silver",  "סמן את הבחור שנשען על המכונית הכסופה",
    [["guy","man","person"],["lean"],["car","vehicle"],["silver"]], 2),
 ("i_flag_low",     "מצא את הדגל שמתנוסס מעל הגג של המבנה הנמוך",
    [["flag"],["fly","wav","hoist","flutter"],["above","over"],["roof"],["building","structure"],["low","short"]], 3),
 # -- superlative + attribute closers --
 ("i_broken_window","הדגש את החלון השבור בקומה התחתונה של הבניין הנטוש",
    [["window"],["broken"],["bottom","lower","ground"],["floor","story","storey"],["building"],["abandoned","deserted"]], 3),
 ("i_last_convoy",  "עקוב אחרי המכונית האחרונה בשיירה",
    [["car","vehicle"],["last"],["convoy","column","caravan","line"]], 2),
 ("i_big_tent",     "סמן את האוהל הגדול ביותר בקצה השדה",
    [["tent"],["big","large"],["edge","end"],["field"]], 2),
 ("i_crane_arm",    "התמקד בזרוע של המנוף שמעל אתר הבנייה",
    [["arm","boom","jib"],["crane"],["above","over"],["construction"],["site"]], 3),
 ("i_boats_pier",   "ספור את הסירות הקשורות למזח הצפוני",
    [["count","how many"],["boat"],["tie","moor"],["north"],["pier","dock","jetty","wharf"]], 2),
]
assert len(INDIRECT_CASES) == 45
assert len({c[0] for c in INDIRECT_CASES}) == 45
