"""40 complex-perception commands (highlight/track/count/find + attributes + spatial).
These are NOT mission-planner cases: in the real system they route to the VLM. Here we measure
whether the TRANSLATION stage preserves the operative keywords. Scoring = keyword-group
preservation: every group must have >=1 accepted synonym as a lowercase substring of the
English translation. Full translations are dumped for owner review (BLEU rejected as opaque)."""
PERCEPTION_CASES = [
 ("p_red_shirt",      "סמן את האדם עם החולצה האדומה",
    [["person","man","human","guy","someone"], ["red"], ["shirt"]]),
 ("p_red_shirt_left", "סמן את האדם עם החולצה האדומה על הבניין בצד השמאלי ביותר",
    [["person","man","guy","someone"], ["red"], ["shirt"], ["building"], ["left"]]),
 ("p_track_white_car","עקוב אחרי המכונית הלבנה",
    [["track","follow"], ["car","vehicle"], ["white"]]),
 ("p_count_yard",     "ספור כמה אנשים יש בחצר",
    [["count","how many"], ["people","persons"], ["yard","courtyard"]]),
 ("p_black_dog",      "מצא את הכלב השחור ליד העץ",
    [["find","locate","spot"], ["dog"], ["black"], ["tree"]]),
 ("p_blue_jacket",    "עקוב אחרי הבחור עם הג'קט הכחול",
    [["track","follow"], ["guy","man","person"], ["blue"], ["jacket","coat"]]),
 ("p_roof_person",    "יש מישהו על הגג של הבניין, סמן אותו",
    [["someone","person","man"], ["roof"], ["building"], ["mark","highlight","tag","point"]]),
 ("p_rightmost_car",  "התמקד ברכב הימני ביותר בחניה",
    [["focus","zoom"], ["car","vehicle"], ["right"], ["parking"]]),
 ("p_between_trees",  "מה נמצא בין שני העצים",
    [["between"], ["trees"]]),
 ("p_crowd_entrance", "כמה אנשים מתקהלים ליד הכניסה לבניין",
    [["how many","count"], ["people"], ["entrance","door"], ["building"]]),
 ("p_yellow_vest",    "סמן את הפועל עם האפוד הצהוב",
    [["worker","laborer","man","person"], ["yellow"], ["vest"]]),
 ("p_kid_bike",       "עקוב אחרי הילד על האופניים",
    [["track","follow"], ["child","kid","boy"], ["bicycle","bike"]]),
 ("p_truck_bridge",   "האם המשאית עברה את הגשר",
    [["truck","lorry"], ["bridge"]]),
 ("p_red_car_road",   "מצא את המכונית האדומה על הכביש הראשי",
    [["find","locate"], ["car","vehicle"], ["red"], ["road","highway","street"]]),
 ("p_woman_umbrella", "סמן את האישה עם המטרייה",
    [["woman","lady"], ["umbrella"]]),
 ("p_men_gate",       "ספור את האנשים שעומדים ליד השער",
    [["count","how many"], ["people","men","persons"], ["gate","entrance"]]),
 ("p_white_van",      "בדוק אם יש טנדר לבן מאחורי הבניין",
    [["van","pickup","truck"], ["white"], ["behind"], ["building"]]),
 ("p_left_window",    "הסתכל על החלון השמאלי בקומה השנייה",
    [["look","watch","check"], ["window"], ["left"], ["second"], ["floor","story"]]),
 ("p_tall_building",  "הדגש את הבניין הגבוה ביותר באופק",
    [["highlight","mark"], ["building"], ["tall","high"], ["horizon","skyline"]]),
 ("p_moto_between",   "סמן את האופנוע שחונה בין שתי המכוניות",
    [["motorcycle","motorbike"], ["park"], ["between"], ["car","vehicle"]]),
 ("p_smoke_field",    "האם יש עשן מעל השדה",
    [["smoke"], ["field"], ["above","over"]]),
 ("p_bird_antenna",   "מצא את הציפור שיושבת על האנטנה",
    [["bird"], ["antenna"]]),
 ("p_open_door",      "בדוק אם הדלת של המחסן פתוחה",
    [["door"], ["warehouse","shed","storage"], ["open"]]),
 ("p_man_running",    "עקוב אחרי האיש שרץ לכיוון הכביש",
    [["track","follow"], ["man","person","guy"], ["run"], ["road","street"]]),
 ("p_green_backpack", "סמן את המטייל עם התיק הירוק",
    [["hiker","traveler","backpacker","person","man"], ["green"], ["bag","backpack","pack"]]),
 ("p_center_frame",   "מה האובייקט הגדול במרכז התמונה",
    [["object","thing"], ["large","big"], ["center","middle"], ["image","frame","picture"]]),
 ("p_bus_stop",       "כמה אנשים מחכים בתחנת האוטובוס",
    [["how many","count"], ["people"], ["bus"], ["stop","station"]]),
 ("p_dog_leash",      "האם הכלב קשור ברצועה",
    [["dog"], ["leash","tied"]]),
 ("p_solar_roof",     "ספור את הפאנלים הסולריים על הגג",
    [["count","how many"], ["solar"], ["panel"], ["roof"]]),
 ("p_red_tractor",    "מצא את הטרקטור האדום בשדה החרוש",
    [["find","locate"], ["tractor"], ["red"], ["field"]]),
 ("p_corner_camera",  "סמן את המצלמה בפינה הימנית העליונה",
    [["camera"], ["corner"], ["right"], ["top","upper"]]),
 ("p_pool_backyard",  "האם יש בריכה בחצר האחורית של הבית",
    [["pool"], ["backyard","back yard"], ["house","home"]]),
 ("p_ladder_wall",    "מצא את הסולם שנשען על הקיר המערבי",
    [["ladder"], ["lean","against","rest"], ["wall"], ["west"]]),
 ("p_convoy",         "עקוב אחרי שיירת שלוש המכוניות",
    [["follow","track"], ["three"], ["car","vehicle","convoy"]]),
 ("p_man_hat_bench",  "סמן את האיש עם הכובע שיושב על הספסל",
    [["man","person","guy"], ["hat","cap"], ["sit"], ["bench"]]),
 ("p_broken_fence",   "בדוק איפה הגדר שבורה",
    [["fence"], ["broken","damaged"]]),
 ("p_cat_shadow",     "מצא את החתול שמתחבא בצל העץ",
    [["cat"], ["hid"], ["shade","shadow"], ["tree"]]),
 ("p_river_boat",     "עקוב אחרי הסירה ששטה בנהר צפונה",
    [["follow","track"], ["boat"], ["river"], ["north"]]),
 ("p_left_of_gas",    "מה יש משמאל לתחנת הדלק",
    [["left"], ["gas","fuel","petrol"], ["station"]]),
 ("p_zoom_plate",     "התקרב ללוחית הרישוי של הרכב הכחול",
    [["zoom","closer","close"], ["plate"], ["car","vehicle"], ["blue"]]),
]

def score_perception(translation, groups):
    t = (translation or "").lower()
    missed = [g for g in groups if not any(s in t for s in g)]
    return missed
