#!/usr/bin/env python3
"""Deterministic case generator -> cases_generated.py. Templated combinatorics over
verbs x amounts (Hebrew number-words AND digits) x phrasings, gender-correct, plus
generated multi-step combos. Run once; the output file is committed so results reproduce."""

# masculine (metrim) number words
M = {1:"מטר אחד",2:"שני מטרים",3:"שלושה מטרים",4:"ארבעה מטרים",6:"שישה מטרים",
     8:"שמונה מטרים",9:"תשעה מטרים",20:"עשרים מטרים",25:"עשרים וחמישה מטרים"}
EN_M = {1:"1 meter"}
DEG = {30:"שלושים מעלות",60:"שישים מעלות",120:"מאה עשרים מעלות",270:"מאתיים שבעים מעלות"}

# verb -> (hebrew phrasings, english phrase, axis, sign)
DIRS = {
 "up":      (["עלה {n}","תעלה {n}"],            "go up {n}",       "z",  1),
 "down":    (["רד {n}","תרד {n}"],              "go down {n}",     "z", -1),
 "fwd":     (["טוס קדימה {n}","התקדם {n}"],     "fly forward {n}", "x",  1),
 "back":    (["טוס אחורה {n}","זוז אחורה {n}"], "fly backward {n}","x", -1),
 "right":   (["טוס ימינה {n}","זוז ימינה {n}"], "fly right {n}",   "y",  1),
 "left":    (["טוס שמאלה {n}","זוז שמאלה {n}"], "fly left {n}",    "y", -1),
}

rows = []
amounts = sorted(M)
for i, (verb, (he_forms, en_form, axis, sign)) in enumerate(DIRS.items()):
    for j, amt in enumerate(amounts):
        he_form = he_forms[(i + j) % len(he_forms)]          # rotate phrasings deterministically
        if (i + j) % 3 == 2:                                  # every 3rd: digit form
            he_n, en_n = f"{amt} מטרים" if amt != 1 else "מטר אחד", f"{amt} meters"
        else:
            he_n, en_n = M[amt], EN_M.get(amt, f"{amt} meters")
        rows.append((f"g_{verb}{amt}", he_form.format(n=he_n), en_form.format(n=en_n),
                     [("fly_by", axis, sign * amt)]))

for deg, he_deg in DEG.items():
    rows.append((f"g_cw{deg}",  f"הסתובב {he_deg} עם כיוון השעון", f"rotate {deg} degrees clockwise",
                 [("spin_by","degrees",deg)]))
    rows.append((f"g_ccw{deg}", f"הסתובב {he_deg} נגד כיוון השעון", f"rotate {deg} degrees counterclockwise",
                 [("spin_by","degrees",-deg)]))

for sec, he_sec in ((2,"שתי שניות"),(10,"עשר שניות")):
    rows.append((f"g_wait{sec}", f"המתן {he_sec}", f"wait {sec} seconds", [("delay","seconds",sec)]))

# generated 2-3 step combos: deterministic pairings of the single-step rows above
singles = [r for r in rows if r[3] and r[3][0][0] == "fly_by"]
for k in range(8):
    a, b = singles[k * 3 % len(singles)], singles[(k * 5 + 7) % len(singles)]
    if a[0] == b[0]: continue
    rows.append((f"g_combo2_{k}", f"{a[1]} ואז {b[1]}", f"{a[2]}, then {b[2]}", a[3] + b[3]))
for k in range(4):
    a, b, c = singles[k*7 % len(singles)], singles[(k*11+3) % len(singles)], singles[(k*13+5) % len(singles)]
    if len({a[0], b[0], c[0]}) < 3: continue
    rows.append((f"g_combo3_{k}", f"{a[1]}, {b[1]} ואז {c[1]}", f"{a[2]}, {b[2]}, then {c[2]}",
                 a[3] + b[3] + c[3]))

with open("cases_generated.py", "w") as f:
    f.write('"""GENERATED by gen_cases.py -- do not hand-edit; regenerate instead."""\n')
    f.write("GENERATED_CASES = [\n")
    for r in rows:
        f.write(f" {r!r},\n")
    f.write("]\n")
print(f"{len(rows)} generated cases")
